### DISCUSSION TITLE
WebView页面将标题栏设置为custom时，安卓上底部显示空白，希望解决一下这个问题

### DISCUSSION THREAD

**Discussion by MilkteaBoy-code** [NervJS/taro#11226] [Q & A]
这是我的代码
index.jsx
```jsx
import { Component } from 'react';
import { View, Text, Button, WebView } from '@tarojs/components';
import Taro from '@tarojs/taro';
import './index.scss'


var interval = null
export default class Index extends Component {

  render() {
    return (
      <View className='aaa' >
          <WebView className='ed' src='https://www.baidu.com' />)
      </View>
    );
  }
}

```

index.scss
```scss


.aaa {
    display: flex;
    // flex: 1;
    width: 100%;
    height: 100%;
    // background-color: red;
    overflow-y:visible ;
}
.ed {
    display: flex;
    flex: 100%;
    background-color: aqua;
    height: 100vh;
    width: 100%;
}
```
app.config.js
```js
export default {
  pages: [
    'pages/index/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
    navigationStyle: 'custom'
  }
}


```

安卓真机上显示效果
<img src="https://i.ibb.co/s9y0Pxm/pic.jpg" alt="pic" border="0" />

平台是京东小程序
