### DISCUSSION TITLE
页面底部出现莫名的空白

### DISCUSSION THREAD

**Discussion by 349989153** [NervJS/taro#11867] [Q & A]
### 相关平台
H5

### 复现仓库
无
**浏览器版本: Chrome 102**
**使用框架: React**

### 复现步骤
想做一个header部分固定，中间内容滚动的页面，页面总共2个子元素：一个固定高度header，一个flex：1的scrollView

页面样式：
```css
{
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
}
```

scrollView样式
```css
{
    flex: 1;
    overflow: scroll;
  }
```

### 期望结果
一个高度100vh，header固定，内容滚动的页面

### 实际结果
页面底部出现空白，且检查元素，无法定位此空白的来源（body元素都在这空白之上）
<img width="1494" alt="taro" src="https://user-images.githubusercontent.com/10381674/171146918-665e99c3-7156-47ff-bd99-0c52701db808.png">

### 环境信息
```
  Taro CLI 3.0.8 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 12.20.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.8 => 3.0.8 
      @tarojs/mini-runner: 3.0.8 => 3.0.8 
      @tarojs/react: 3.0.8 => 3.0.8 
      @tarojs/runtime: 3.0.8 => 3.0.8 
      @tarojs/taro: 3.0.8 => 3.0.8 
      @tarojs/webpack-runner: 3.0.8 => 3.0.8 
      babel-preset-taro: 3.0.8 => 3.0.8 
      eslint-config-taro: 3.0.8 => 3.0.8 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 

```
