### DISCUSSION TITLE
SCSS的url引用图片问题

### DISCUSSION THREAD

**Discussion by lihengdao666** [NervJS/taro#17247] [Q & A]
当我尝试使用相对路径时，可以正确加载图片，并转换为Base64格式
```css
.main-button {
  background-image: url("../../static/yeh.png");
  background-position: right bottom;
  background-repeat: no-repeat; 
  background-size: 90px;
}
```
而当我使用~符号时，url的图片地址并没有转义成base64，而是一个奇怪的地址
```css
.main-button {
  background-image: url("~/src/static/yeh.png");
  background-position: right bottom; 
  background-repeat: no-repeat; 
  background-size: 90px;
}
```
这里转义后我得到了
```css
background-image:url(/static/yeh.png-do-not-use-local-path-./pages/index/index.wxss&39&20)
```
我尝试重新创建项目依然会出现这个问题
