### ISSUE TITLE
less  中 变量  无法编译

### ISSUE THREAD

**Issue by myNameCao** [NervJS/taro#11606]
### 相关平台
微信小程序

### 复现仓库
[https://git.xiaoyanggroup.cn/xycx/front/miniwechat.git](https://git.xiaoyanggroup.cn/xycx/front/miniwechat.git)
**小程序基础库: 2.23.3**
**使用框架: Vue 2**

### 复现步骤
```less

  @w: 100/1334vw;
  @h: 100/750vh;
  @bg: #0080ff;
  .handleBtn {
    width: 100%;
    height: 78 * @h;
    position: absolute;
    bottom: 5px;
}


```

### 期望结果
可以编译

### 实际结果
无法编译

### 环境信息
```
Taro CLI 3.4.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.4 => 3.4.4 
      @tarojs/components: 3.4.4 => 3.4.4 
      @tarojs/mini-runner: ^3.4.4 => 3.4.4 
      @tarojs/runtime: 3.4.4 => 3.4.4 
      @tarojs/taro: 3.4.4 => 3.4.4 
      @tarojs/webpack-runner: 3.4.4 => 3.4.4 
      babel-preset-taro: 3.4.4 => 3.4.4 
      eslint-config-taro: 3.4.4 => 3.4.4 
```
