### ISSUE TITLE
小程序 page config 中配置 backgroundColor 无效

### ISSUE THREAD

**Issue by zoux** [NervJS/taro#1181]
设置 navigationBarTitleText 是有效的，而在 config 对象里设置 backgroundColor 并赋值如'#f7f7f7'，页面中并未生效。

目前暂时通过 min-height: 100vh + background 的方式实现的。

**Comment by luckyadam** [comment]
代码贴一下

**Comment by jeffhuang2086** [comment]
@zoux   config中的backgroundColor属性是设置窗口的背景色，这种在下拉刷新时能看到！想要设置page的背景色直接在css文件，加如下代码
```
page {
  background-color: #ccc;
}
```

**Comment by jethroHuang** [comment]
> 这个issue怎么关掉了？这不算解决了问题吧，用css的话我还要解决如何把容器撑开的问题

不用考虑撑开的问题，直接写page的就行了

**Comment by shzjj82** [comment]
那如果在react native端 page是不支持的啊

**Comment by edwardfxiao** [comment]
@jeff-fe 
```css
page {
  /*background-color: #ccc;*/ // 生效
  background-color: var(--myBackgroundColor); // 为什么不生效
}
.myTextClass {
  background-color: var(--myBackgroundColor); // 生效
}
```

想问一下为什么var的方法就单独page不可行?
