### ISSUE TITLE
多个样式编译报错

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#11984]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
编译报错的样式
border-bottom: 1px solid #e2e2e2;
font-weight: 600;
/*  #ifndef rn  */
这里面的样式会被编译
/*  #endif  */

### 期望结果
编译通过

### 实际结果
不通过

### 环境信息
```
Taro v3.5.0-beta.2


  Taro CLI 3.5.0-beta.2 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1656043735120-0.4507388907002723/node
      Yarn: 1.22.18 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1656043735120-0.4507388907002723/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/components: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/mini-runner: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/plugin-framework-react: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/react: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/rn-runner: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/runtime: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/taro: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/taro-rn: 3.5.0-beta.2 => 3.5.0-beta.2 
      @tarojs/webpack-runner: 3.5.0-beta.2 => 3.5.0-beta.2 
      babel-preset-taro: 3.5.0-beta.2 => 3.5.0-beta.2 
      eslint-config-taro: 3.5.0-beta.2 => 3.5.0-beta.2 
      expo: ~45.0.5 => 45.0.5 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.68.2 => 0.68.2 

```

**Comment by zhiqingchen** [comment]
https://github.com/wuba/taro-playground/blob/releases/v1.6.0/src/pages/global/pages/styles/platform.scss

**Comment by zhiqingchen** [comment]
对比下与demo写法是否一致

**Comment by ShaoGongBra** [comment]
`/*  #ifndef  weapp rn  */`这中间的空格也要一一对上吗，不然没道理不对呀，这个代码在taro3.4都是能用的

**Comment by ShaoGongBra** [comment]
```css
/*  #ifndef  rn  */
    textarea {
      font-size: 26px;
      outline: none;
      resize: none;
    }
    /*  #endif  */
```
我是这样写的

**Comment by zhiqingchen** [comment]
```
    textarea {

/*  #ifndef  rn  */
      font-size: 26px;
      outline: none;
      resize: none;
    /*  #endif  */
    }
```

**Comment by ShaoGongBra** [comment]
> ```css-scss
>     textarea {
> 
>       /*  #ifndef  rn  */
>       font-size: 26px;
>       outline: none;
>       resize: none;
>       /*  #endif  */
>     }
> ```

后面打算修复一下吗，要修武，我就不改了，这个也是个npm的包

**Comment by zhiqingchen** [comment]
> ```css
> /*  #ifndef  rn  */
>     textarea {
>       font-size: 26px;
>       outline: none;
>       resize: none;
>     }
>     /*  #endif  */
> ```
> 
> 我是这样写的

@shinken008 这个是可以支持的吗

**Comment by shinken008** [comment]
目前只支持在类里面条件编译，应该可以支持的，样式里面有挺多需要优化的地方~

**Comment by shinken008** [comment]
> 不然没道理不对呀，这个代码在taro3.4都是能用的

如果使用 css 写的代码注释，这样的注释是 ok 的， 如果是 sass less 等，注释处理之后不能编译到 rule 的位置，比如：
```scss
.rule {
    /*  #ifndef  h5  */
    h1 {margin: 0 0 20px;font-size: 40Px;line-height: 1.2;}
    /*  #endif  */ 
    .test{}
  }
```
处理css后是：
```css
.rule {
  /*  #ifndef  h5  */
  /*  #endif  */
}
.rule h1 {
  margin: 0 0 20px;
  font-size: 40Px;
  line-height: 1.2;
}
```
注释只能用于rule 里面，不能作用于标签
