### ISSUE TITLE
Input controlled 模式无效

### ISSUE THREAD

**Issue by nuintun** [NervJS/taro#12211]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/nuintun/taro](https://github.com/nuintun/taro)

**小程序基础库: 2.52.2**
**使用框架: React**

index.module.scss
```scss
.inputNumber {
  width: 176px;
  display: flex;
  min-height: 54px;
  position: relative;
  border-radius: 8px;
  align-items: center;
  box-sizing: border-box;
  background-color: #fff;
  border: 1px solid #e1e1e1;

  .input {
    outline: none;
    padding: 0 2px;
    font-size: 28px;
    text-align: center;
  }

  .decrease {
    border-right: 1px solid #e1e1e1;
  }

  .increase {
    border-left: 1px solid #e1e1e1;
  }

  .decrease,
  .increase {
    image {
      width: 48px;
      height: 48px;
      vertical-align: middle;
    }

    &.disabled {
      image {
        opacity: 0.12;
      }
    }
  }
}
```

index.tsx
```tsx
import styles from './index.module.scss';

import React, { memo, useCallback, useMemo } from 'react';

import classNames from 'classnames';
import useControllableValue from '/hooks/useControllableValue';
import { BaseEventOrig, Image, Input, InputProps, View } from '@tarojs/components';

import Plus from '/images/icon-input-plus.svg';
import Minus from '/images/icon-input-minus.svg';

export interface InputNumberProps extends Omit<InputProps, 'value'> {
  min?: number;
  max?: number;
  step?: number;
  value?: number;
  controls?: boolean;
  defaultValue?: number;
  prefix?: React.ReactNode;
  suffix?: React.ReactNode;
  onChange?: (value: number) => void;
}

function resolveValue(value: number, props: InputNumberProps): number {
  const { min, max } = props;

  if (min != null && value < min) {
    return min;
  }

  if (max != null && value > max) {
    return max;
  }

  return value;
}

export default memo(function InputNumber(props: InputNumberProps): React.ReactElement {
  const { min, max, step = 1, className, disabled, controls = true, ...restProps } = props;

  const [value = 0, setValue] = useControllableValue<number>(props);

  const onIncrease = useCallback(() => {
    if (!disabled) {
      setValue((value = 0) => resolveValue(value + step, props));
    }
  }, [min, max, step, disabled]);

  const onDecrease = useCallback(() => {
    if (!disabled) {
      setValue((value = 0) => resolveValue(value - step, props));
    }
  }, [min, max, step, disabled]);

  const onInput = useCallback(
    (e: BaseEventOrig<InputProps.inputValueEventDetail>) => {
      const input = +e.detail.value;

      if (!Number.isNaN(input)) {
        const nextValue = resolveValue(input, props);

        setValue(nextValue);

        return nextValue;
      }

      return value;
    },
    [value, min, max]
  );

  const [increaseClassName, decreaseClassName] = useMemo(() => {
    const { disabled: disabledClassName } = styles;

    return [
      classNames(styles.increase, { [disabledClassName]: max == null ? disabled : value >= max }),
      classNames(styles.decrease, { [disabledClassName]: min == null ? disabled : value <= min })
    ];
  }, [value, min, max, disabled]);

  return (
    <View className={classNames(styles.inputNumber, className)}>
      {controls && (
        <View className={decreaseClassName} onClick={onDecrease}>
          <Image src={Minus} />
        </View>
      )}
      <Input
        {...restProps}
        controlled
        type="number"
        onInput={onInput}
        confirmType="done"
        cursorSpacing={50}
        disabled={disabled}
        value={value.toString()}
        className={classNames('ui-input usn', styles.input)}
      />
      {controls && (
        <View className={increaseClassName} onClick={onIncrease}>
          <Image src={Plus} />
        </View>
      )}
    </View>
  );
});
```

### 复现步骤
输入，无法限定 Input 值
受控和非受控模式很怪异，非受控，除了初始化后面修改 value 不应该更新视图，受控才应该修改。
现在 controlled 模式就像个摆设！
不如学习 React Input 用 defaultValue 和 value 区分受控和非受控😁

### 期望结果
受控模式生效

### 实际结果
受控模式无效

### 环境信息
```
👽 Taro v3.5.1

  Taro CLI 3.5.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\nuintun\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
```

![input](https://user-images.githubusercontent.com/1730277/182562187-d8601536-98f4-4fcc-80ec-6b2e7a568b98.gif)
