### ISSUE TITLE
H5页面在ipad尺寸上View的高宽比发生了变化

### ISSUE THREAD

**Issue by Zoom2016** [NervJS/taro#1396]
**问题描述**
[问题描述：一个简单的页面 View设置了固定的高度，但在ipad上高宽比发生了变化，导致里面的图片缺失了一部分，直接看代码吧。。]

**复现步骤**
[复现问题的步骤]
1、没步骤

[或者可以直接贴源代码，能贴文字就不要截图]
```css
.error {
  background: rgba(233, 230, 255, 1);
  .part1 {
    width: 100%;
    // height: 100vw;
    height: 1000px;
    background: url('../../../src/assets/image/error/1.png') no-repeat center;
    background-size: 100%;
    position: relative;
  }

  .part2 {
    width: 100%;
    height: 500px;
    background: url('../../../src/assets/image/error/2.png') no-repeat center;
    background-size: 100%;
    position: relative;
  }
  .part3 {
    width: 100%;
    height: 500px;
    background-color: crimson;
    position: relative;
  }
}
```

```html
      <View className='error'>
        <ScrollView >
          <View className='part1' />
          <View className='part2' />
          <View className='part3'>
          </View>
        </ScrollView>
      </View>
```

**期望行为**
[每块view里面是一张背景图，我期望能在不同的尺寸屏幕下面图片等比例放大缩小，但实际在ipad尺寸下面图片的上下部分会被吃掉。。]

**报错信息**
![default](https://user-images.githubusercontent.com/24583558/49566603-2f479180-f966-11e8-914c-854b4a0752b6.jpg)
![ipad](https://user-images.githubusercontent.com/24583558/49566700-9c5b2700-f966-11e8-93ac-4b91a70cf455.jpg)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.1.7]
 - Node.js 版本 [e.g. v8.11.1]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
编译后height的的单位从px转成rem， 不同尺寸下面的rem值相同，但font-size发生了变化，最后导致div的 尺寸比例发生了变化
