### ISSUE TITLE
css预处理器（sass）@import 异常

### ISSUE THREAD

**Issue by zhoucs624** [NervJS/taro#1474]
**问题描述**
css预处理器（sass）在app.scss中引入mixin.scss后，此后mixin.scss的更改并没有在app.scss编译后的代码（app.wxss)中

**复现步骤**
1. 新建mixins.scss，并将其导入到app.scss中
2.修改mixins.scss的某个属性
3. 保存后自动编译

`before`
```css
 // mixins.scss
.header {
    font-size: 14PX;
}

// app.scss
@import './mixins.scss';

.header {
    color: blue;
}
```

`after`
```css
 // mixins.scss
.header {
    font-size: 17PX;
}

// app.scss
@import './mixins.scss';

.header {
    color: blue;
}
```

**期望行为**
mixin.scss修改保存后，编译后的代码出现修改的内容

**系统信息**

 - 操作系统: macOS 10.14
 - Taro 版本: 1.1.9
 - Node.js 版本: 8.11.3
 - 报错平台: weapp
