### ISSUE TITLE
scss 文件有没有计划支持引入别名配置

### ISSUE THREAD

**Issue by kycool** [NervJS/taro#1634]
场景：
全局定义了通用的模块，例如名字叫做 common.scss，里面定义的内容如下

```scss
.p-l-10 {
    padding-left: 10px;
}
```

接着自定义了一个组件，自定义组件有对应的样式文件，例如叫做 custom.scss, 例如当前的写法如下

```scss
@import '../.../../styles/common.scss'

...
```

为了避免在 custom.scss 中写入多层的相对路径，taro 有没有计划支持引入 postcss-import，可以支持
自定义路径别名，类似当前 alias

@yuche
