### ISSUE TITLE
使用scss mixin时，大写PX仍然会被转换

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#1786]
在var.scss中
```scss
$fz: 16PX;
```

在mixin中
```scss
@import './var.scss'
@mixin foo{
  font-size: $fz;
}
```

然后在components的scss中使用
```scss
@import '@styles/mixin.scss';
.bar{
  @include foo;
}
```

打包成h5，发现大写的PX仍然被转化成了rem

**Comment by Pines-Cheng** [comment]
我这里尝试了一下，没有重现额。@loveonelong
```scss
$fz: 16PX;

@mixin foo{
  font-size: $fz;
}

.bar{
  @include foo;
}

```

**Comment by loveonelong** [comment]
@Pines-Cheng 写在不同的文件里试一下

**Comment by Pines-Cheng** [comment]
在不同文件也没问题。
转换后：

```css
.index{width:100%}.bar{font-size:16PX}
```
