### ISSUE TITLE
满屏问题

### ISSUE THREAD

**Issue by hrh94** [NervJS/taro#1795]
我在一个View上的样式：
```
width: 100%;
height: 100%;
```
希望这个View能够铺满整个屏幕，但是实际上却没有产生效果。
PS：开发支付小程序时出现的问题

**Comment by loveonelong** [comment]
这并非是bug.
你可以看一下微信控制台wxml生成的节点中，最外层被包了page标签，这是微信自带的。
其次，你可以通过`page{height: 100%;} `或是`.your-view{height: 100vh}`等方法来实现。

**Comment by loveonelong** [comment]
建议你巩固一下自己的css基础

**Comment by dushaobindoudou** [comment]
我觉得 vh 用法是hack，配置page 更是影响全局，引入不确定性，本身的支持情况有问题，让别人去学习css，恕我直言 垃圾

**Comment by loveonelong** [comment]
@dushaobindoudou Page满屏的问题是微信小程序本身的问题，跟Taro没有关系。

**Comment by dushaobindoudou** [comment]
首先这个是H5的问题，请仔细看问题，其次，我用的体验非常不好

**Comment by loveonelong** [comment]
@dushaobindoudou 如果你觉得有更好的方案，欢迎pr

**Comment by ouzhou** [comment]
小程序需要吧page 也设置成100%，子节点100%才能全屏
```
page{
  height: 100%;
}
```

h5结构在v3.x可以使用
```
.taro_router {
  height: 100%;
  > div {
    height: 100%;
    .taro_page{
      height: 100%;
    }
  }
}

```

**Comment by bang88** [comment]
Nice 

```css
html,
body {
  height: 100%;
  .taro-tabbar__container,
  .taro_router {
    height: 100%;
    > div {
      height: 100%;
      .taro_page {
        height: 100%;
      }
    }
  }
}

```
