### ISSUE TITLE
开启css module，无法使用less的混合功能，编译小程序报错（H5正常）

### ISSUE THREAD

**Issue by zhangzhenfei** [NervJS/taro#1799]
index.module.less

```less
.textOverflow() {
  width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  word-break: break-all;
  word-wrap: break-word;
  white-space: nowrap;
}

.products {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  padding: 30px;
}

.item {
  &.two {
    box-sizing: content-box;
    width: 49%;
    &:not(:nth-child(2n)) {
      padding-right: 2%;
    }
  }
  &.three {
    box-sizing: content-box;
    width: 32%;
    &:not(:nth-child(3n)) {
      padding-right: 2%;
    }
  }
}

.imgWrap {
  position: relative;
  padding-bottom: 74.66%;
  overflow: hidden;
}

.img {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
}

.contentWrap {
  padding: 15px;
}

.title {
  font-size: 28px;
  color: #202020;
  margin-top: 20px;
  .textOverflow();
}

.desc {
  font-size: 24px;
  color: #888888;
  margin-top: 10px;
  .textOverflow();
}

.priceWrap {
  display: flex;
  align-items: baseline;
  // color: @primary-color;
  margin-top: 10px;
}

.price {
  font-size: 32px;
  font-weight: 500;
}

.originPrice {
  font-size: 24px;
  color: #999999;
  padding-left: 8px;
  text-decoration: line-through;
}
```
dev:weapp 报错，dev:h5正常

错误  页面编译  页面/Users/syt/private-project/mp-shopping-mall/src/pages/index/index编译失败！
TypeError: Cannot read property 'wxss' of undefined
    at buildDepComponentsResult.map.item (/Users/syt/.nvm/versions/node/v8.11.3/lib/node_modules/@tarojs/cli/src/weapp.js:1639:23)
    at Array.map (<anonymous>)
    at getDepStyleList (/Users/syt/.nvm/versions/node/v8.11.3/lib/node_modules/@tarojs/cli/src/weapp.js:1638:44)
    at buildSinglePage (/Users/syt/.nvm/versions/node/v8.11.3/lib/node_modules/@tarojs/cli/src/weapp.js:1397:28)
    at <anonymous>
