### ISSUE TITLE
RN设置高度100%，应该是disableScroll:true

### ISSUE THREAD

**Issue by bobchow** [NervJS/taro#1853]
**问题描述**
RN设置高度100%，应该是disableScroll:true，文档应该是写错了
![image](https://user-images.githubusercontent.com/2377207/50813123-5243d780-1350-11e9-849d-fa4cbe7d0ec4.png)

**复现步骤**
在页面设置config中添加：disableScroll:true
然后css设置：height: 100%，测试RN，可以看到100%高度的效果
设置disableScroll:false后，无法看到100%高度的效果

```js
config = {
    navigationBarTitleText: '登录',
    disableScroll: true
  }
```
```css
.page-verify-phone{
  background-color: #f8f9fd;
  height: 100%;
}
```

**期望行为**
希望能更正下文档

**报错信息**
无

**系统信息**
 - 操作系统: [Windows 10]
 - Taro 版本 [1.2.4]
 - Node.js 版本 [10.14.0]
 - 报错平台 [RN]

**补充信息**
无
