### ISSUE TITLE
RN 端是否已兼容 CSS Modules？

### ISSUE THREAD

**Issue by js-newbee** [NervJS/taro#1894]
**问题描述**
[CSS Modules](https://nervjs.github.io/taro/docs/css-modules.html) 这一章节的文档说“1.2.0 版本开始支持，RN 端已兼容”，但是拿这个文档的示例代码进行测试，发现样式没有效果。

查看编译后的代码，发现样式引用编译成：style={_getStyle(_styleSheet.test)}
但 _styleSheet.test 的类型是 number，_getStyle 对 number 类型并没有处理，最终得到的 style 是 [undefined]

**复现步骤**
代码均从 [CSS Modules](https://nervjs.github.io/taro/docs/css-modules.html) 中 copy 而来

**期望行为**
样式正确

**报错信息**
无报错

**系统信息**
 - 操作系统: macOS High Sierra 10.13.6
 - Taro 版本: v1.2.4
 - Node.js 版本: v10.9.0
 - 报错平台: RN

**补充信息**

粗略来看，有几种种解决方式：
1. 使用 CSS Modules 时，输出的样式直接就是 {_styleSheet.test}？
2. 使用 CSS Modules 时，输出的样式应该是 {_getStyle(‘test’)}，而不是 {_getStyle(_styleSheet.test)} ?
3. _getStyle 中对 number 类型进行处理，如果是 number，就直接输出就好了，应该跟方式1是一样的

如果这块支持确实存在问题，那以何种解决方式合适？有需要我可以提个 pr

**Comment by Pines-Cheng** [comment]
现在 React 的 RN 端对于  CSS Modules 的支持准确来说仅支持了  CSS Modules 的的写法，使其能够正常运行。现在碰到的核心问题是，RN 中的样式没有嵌套和层级的概念，导致以下的写法都不支持：

```css
.button.button_theme_islands{
  font-style: bold;
}

img + p {
  font-style: bold;
}

p ~ span {
  color: red;
}

div > span {
  background-color: DodgerBlue;
}

div span { background-color: DodgerBlue; }
```

因此导致 CSS Modules 在 RN 中收益极其有限。

如果能够有好的想法在编译的过程中对以上的写法进行支持，那就完美了。@js-newbee
