### ISSUE TITLE
build后，scss有时会丢失样式

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro#2060]
**问题描述**
dev模式下没问题，build后，有时会出现生成的wxss文件变成空的，

`index.scss`

```css
@import '../../style/goods.wxss';
@import '../../style/shared.wxss';
.goods-list-select {
  display: flex;
  align-items: center;
}

```

build后开始是有内容的，用微信小程序开发者工具，刷新 下页面，然后，有时就变成空的了

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: osx 10.14
 - Taro 版本 1.2.3
 - Node.js 版本 10.05
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
