### ISSUE TITLE
百度小程序 父组件的列表数据 在追加数据后 有时候 子组件接受不到 新的数据

### ISSUE THREAD

**Issue by prenukes** [NervJS/taro#2245]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

百度小程序 父组件的列表为一个数组  在上拉加载后追加新数据后 有时候 子组件接受不到 新的数据
 例如下图  父组件的list长度为110  子组件的list长度为100  新追加的10条数据 未被子组件接收到

此类问题有时候可以复现 有时候正常

**在正式的项目中  子组件 样式嵌套过多的话 就经常出现 此类问题**

![image](https://user-images.githubusercontent.com/32321422/53226772-1aea7980-36b7-11e9-9e23-c094f1902e7c.png)

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
//index.js
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import List from '../../components/list/list'
import './index.less'

export default class Index extends Component {

  constructor(props) {
    super(props);
    this.state = {
      list: [1,2,3,4,5,6,7,8,9,0]
    }
  }

  config = {
    navigationBarTitleText: '首页'
  }

  onReachBottom() { //触发底部加载
    // console.log('触发底部加载')
    // this.loadMore()
    Taro.showLoading({
      title: '请求中...',
      mask: true,
    })
    setTimeout(()=> {
      let lists = [...this.state.list]
      lists = lists.concat([1,2,3,4,5,6,7,8,9,0])
      this.setState({
        list: lists
      }, () => {
        Taro.hideLoading()
        console.log('父组件:', this.state.list.length)
      })
    }, 1000)
  }
  render () {
    return (
      <View className='index'>
        <List data={this.state.list} />
      </View>
    )
  }
}

//list.js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import './list.less'

export default class List extends Component {
    render() {
        const list = [...this.props.data]
        console.log('组件内部：', list.length)
        return(
            <View>
                {list.map(v=> {
                    return(
                        <View>{v}</View>
                    )
                })}
            </View>
        )
    }
}

List.defaultProps = {
    data: []
}



```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

� Taro v1.2.7
  Taro CLI 1.2.7 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
可以先升级到最新版本试试

**Comment by prenukes** [comment]
> 可以先升级到最新版本试试

已升级到最新版本 还是为出现 上述问题
![image](https://user-images.githubusercontent.com/32321422/53311127-96803c80-38ea-11e9-953f-f4f475ec20d3.png)
� Taro v1.2.13


  Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD


![image](https://user-images.githubusercontent.com/32321422/53311164-bdd70980-38ea-11e9-9bf5-500f707e6a42.png)

**Comment by Chen-jj** [comment]
@prenukes 感谢老哥你的 demo，问题已经定位到，和百度 properties 的 observer 触发时序有关系，正在和百度方面沟通。

**Comment by Sweet-KK** [comment]
我也遇到同样的问题,更新了页面的state,子组件没能收到新的props,希望快点解决,否则项目无法上线呀~~~
![image](https://user-images.githubusercontent.com/29600932/55540005-97c83480-56f4-11e9-82bf-6d7ce72a0d46.png)

**Comment by Chen-jj** [comment]
@Sweet-KK 百度方面说清明后给答复，我们也会尽快尝试其它手段绕过此问题

**Comment by Sweet-KK** [comment]
> @Sweet-KK 百度方面说清明后给答复，我们也会尽快尝试其它手段绕过此问题

这个问题怎么样了,我现在只要使用到组件都会出现这种情况,包括taro UI,要是短时间内解决不了,就不能使用组件了,还得把之前用的组件都改掉,自己实现并且代码写到页面上,数据才能同步变化~~~难受

**Comment by meicx** [comment]
> @Sweet-KK 百度方面说清明后给答复，我们也会尽快尝试其它手段绕过此问题

这个问题怎么样了啊

**Comment by Great-old-one** [comment]
解决了吗？ 项目无法上线

**Comment by Chen-jj** [comment]
@Great-old-one 下周会发一个测试版本

**Comment by Chen-jj** [comment]
各位可以更新到 v1.2.27-beta.0 后再试试

**Comment by Sweet-KK** [comment]
更新了1.2.27-beta.0之后 iconfont不显示了。之前的版本是可以的

**Comment by Chen-jj** [comment]
@Sweet-KK 提供可复现代码

**Comment by Sweet-KK** [comment]
**问题描述**
更新到版本1.2.27-beta.0后，iconfont不显示，之前的版本：字体文件不管是网络链接还是本地文件都可以正常显示的

**复现步骤**
```js
// 这里可以贴代码
// icon.scss
@font-face {font-family: "iconfont";
  src: url('./assets/font/iconfont.eot'); /* IE9 */
  src: url('./assets/font/iconfont.eot') format('embedded-opentype'), /* IE6-IE8 */
  url('./assets/font/iconfont.woff') format('woff'),
  url('./assets/font/iconfont.ttf') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
  url('./assets/font/iconfont.svg') format('svg'); /* iOS 4.1- */
}
.icon {
  font-family: "iconfont" !important;
  font-size: 16px;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.icon-weixin:before {
  content: "\e600";
}

// app.js
import '@tarojs/async-await';
import Taro, { Component } from '@tarojs/taro';
import Index from './pages/index';

import './icon.scss'
import './variables.scss';
import './app.scss';

// index.js
import Taro, { Component } from '@tarojs/taro'
import { AtIcon } from 'taro-ui'
import { View } from '@tarojs/components'
import './index.scss'


export default class Index extends Component {
  render() {
    return (
      <View className='index'>
        <AtIcon prefixClass='icon' value='weixin' size='14'></AtIcon>  
      </View>
    )
  }
}

```

**期望行为**
字体正常显示

**报错信息**
没有报错

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [Taro v1.2.27-beta.0]
 - Node.js 版本 [v10.15.3]
 - 报错平台 [swan, weapp]

**Comment by Sweet-KK** [comment]
能复现出来么？

**Comment by Chen-jj** [comment]
@Sweet-KK 复现不了。

1. 随便下载一个 iconfont

![image](https://user-images.githubusercontent.com/11807297/56499873-f7b73b80-653a-11e9-89ab-fdc413f25440.png)

```css
@font-face {font-family: "iconfont";
  src: url('iconfont.eot?t=1555934768215'); /* IE9 */
  src: url('iconfont.eot?t=1555934768215#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('data:application/x-font-woff2;charset=utf-8;base64,d09GMgABAAAAAALMAAsAAAAABowAAAJ+AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHEIGVgCCcAqBEIEsATYCJAMICwYABCAFhG0HNRvXBcgOJU0bwQgUggBABM/v923Oe/erpl3EPZkmMmk7kU8kiZZMIq1kzLtopq0crbU5XPrQz+MnzJLq3uyJ7w2WSIQG8UOmZJUEoRHxiXunfwIFMt95l8sYg8aaNOlfgHEgBbQ3RpGVSOYNYxe4hMcEqhbRaSemF1egTWKtCsRE6B9CWy4iSSxfFoo1B5O4q6Cc3c5eAnfC78c/brSRKeSspvPXpzwY/XVhF+WjhZFrPiFKQMcLyLEBSMTl2sxZjYLxGlUzTZaBfdUHv24uLPhusVeHYH+dVVsHY1B5TypXfauSGUiMZj1wctRN5L16142Vq9Hw6vUTLW4N19aDDY+3Pj5WPn2ufvle//x15ujXInm2+ePH1p7/p8vaRrymY1Xz5vbtvcCedttnNVf7TZNpdhbqJil3Mm2ufdtcz9+9a6xjGZJ7WjwBRgEWZhrxb0ZBQ/DsuT6133vgf7mWwNdvz3YYWphpgn4+UD6TN/hjqp6cpGssV5ZUVW0hs17jnbRUVbEAB7p+x1oHt1cIZYOb9JWMp8iVrSATuwEFNTtQVHYYVevNHK/pURpFqmCdS4DQdoNM0zRybY9kYn9QMPSHonY0oupq9C6sWRVhx3FFh0weHp1jKPJMOh7uiOqXyD9ODlVWE/LXSFVhHB3TLuZnKCM1x5bqxHeZJUqVpzgNnqMkybFQeUSCzYC5qFmWrHuTKfIUOhynkEOMeNCRcygk5DLSH8w6Sp9fQnzHEodUS09Neg1RKuH4yGGye5AzxqxXz728UjnhczEmIUnJpdA0mEcSiRwq6udFiMBMwYhUocay+8m+RnN9c/p1h6DKsmVh78zVJkiyIUIlEgIAAAA=') format('woff2'),
  url('iconfont.woff?t=1555934768215') format('woff'),
  url('iconfont.ttf?t=1555934768215') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
  url('iconfont.svg?t=1555934768215#iconfont') format('svg'); /* iOS 4.1- */
}

.iconfont {
  font-family: "iconfont" !important;
  font-size: 16px;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.iconfont-left-circle:before {
  content: "\e77f";
}
```

2. 全局引入此 iconfont

![image](https://user-images.githubusercontent.com/11807297/56499880-0d2c6580-653b-11e9-9c64-18530b3feff0.png)

3. 使用

```js
export default class Detail extends Component {
  render() {
    return (
      <View>
        <View>
          icon:
          <AtIcon prefixClass='iconfont' value='left-circle' size='30'></AtIcon>
        </View>
      </View>
    )
  }
}
```

4. 成功显示

![image](https://user-images.githubusercontent.com/11807297/56500020-b5dac500-653b-11e9-8427-49b657767e15.png)
