### ISSUE TITLE
taro 编译成百度小程序时，父组件 setState，子组件无法正常接收

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#2323]
**复现步骤**
[复现问题的步骤]
1. 直接点击登录

[或者可以直接贴源代码，能贴文字就不要截图]

### 父组件
```js
import {
  Block,
  Form,
  View,
  Image,
  Button,
  Text,
  Navigator
} from '@tarojs/components'
import Taro from '@tarojs/taro'
import RegisterModal from '../../components/register-modal/index'

let defaultAvatar = 'https://avatars3.githubusercontent.com/u/25219300?s=40&v=4';
class UserPage extends Taro.Component {
  state = {
    UserInfo: {
      resumeIntegrity: 0,
      avatar: defaultAvatar
    },
    name: '',
    hasLogined: false,
    showLoginWays: false
  };

  pageSubmit = e => {
    let { dataset } = e.detail.target;
    dataset.formId = e.detail.formId;
    console.log("showLoginWays")
    this.setState({
      showLoginWays: true
    })
  }


  closeLogin = () => {
    this.setState({
      showLoginWays: false
    })
  }

  config = {
    enablePullDownRefresh: true,
    navigationBarTitleText: '我的'
  }

  render() {
    const {
      name,
      hasLogined,
      description,
      UserInfo,
      showFeedback,
      showLoginWays,
      showToast,
      showToastTitle
    } = this.state;

    return (
      <Block>
        <Form reportSubmit onSubmit={this.pageSubmit}>
          <View className='container'>
            <Button
              className='user_box userinfo flex space_between a_center'
              data-st='listGoto'
              onTouchEnd={this.reportSt}
              data-nav='/pages/resume/preview'
              data-event='ENTER_PAGE_RESUME'
              formType='submit'
              hoverClass='none'
            >
              <View className='info_box'>
                <View className='name'>{name || '点击登录'}</View>
                <View className='introduction single_line_ellipsis'>
                  {hasLogined ? description : '登录后查看更多信息'}
                </View>
              </View>
              <View className='avatar_box'>
                <View hoverClass='none'>
                  <Image
                    className='avatar_img'
                    src={UserInfo.avatar}
                    mode='aspectFill'
                  />
                </View>
              </View>
            </Button>
            <View className='more_info'>
              <View>

              </View>
            </View>
          </View>
        </Form>
        <RegisterModal
          onLoginSuccess={this.loginSuccess}
          onCloseLogin={this.closeLogin}
          show={showLoginWays}
        />
      </Block>
    )
  }
}

export default UserPage

```

### 子组件
```js
import { Block, View, Form, Button, Image, Text } from '@tarojs/components'
import Taro from '@tarojs/taro'
import withWeapp from '@tarojs/with-weapp'
import Classnames from 'classnames'
import Toast from '../toast/index'
import './index.scss'

@withWeapp('Component')
class _C extends Taro.Component {
  constructor(props) {
    super(props);
  }
  static defaultProps = {
    show: false,
    title: '登录或注册',
    closeJump: false
  }
  closeLoginJump = () => {
    this.props.onCloseLogin()
  }


  config = {
    component: true
  }

  render() {
    let {
      showPhoneRegisterModal: showPhoneRegisterModal,
      phoneNumber: phoneNumber,
      showToast,
      showToastTitle
    } = this.state;
    let { show, title } = this.props;
    let getClassName = 'modal invite flex flex_center register-modal ' + (show ? '' : 'hide')

    return (
      <Block>
        <View
          className={getClassName}
          onTouchMove={this.preventScroll}
        >
          <View >
            <View className='login_way_model ta'>
              <Button
                className='close_login flex flex_center'
                onClick={this.closeLoginJump}
                data-event='CLICK_CLOSE'
              >
                关闭按钮
              </Button>
              <View className='title'>{title}</View>
              <Button
                className='wx_btn wx_login flex flex_center'
                hoverClass='wx_btn_hover'
                data-event='CLICK_WECHAT_PHONE'
                openType='getPhoneNumber'
                onGetPhoneNumber={this.getPhoneNumber}
              >
                <Image
                  className='icon icon-wechat'
                  src={this.registerLogo}
                />
                <Text decode className='litter'>
                  {this.registerBtnText}帐号快速登录
                </Text>
              </Button>
              <Button
                data-type='register'
                className='mobile_btn mobile_number_login flex flex_center'
                hoverClass='mobile_btn_hover'
                data-event='ENTER_PAGE_PASSPORT_REGISTER'

              >
                <Image
                  className='icon icon-mobile'
                  src='https://static.lagou.com/wx-mina/static/asset/common/icon-mobile_9140c68.png'
                />
                <Text decode className='litter'>
                  手机号注册/登录
                </Text>
              </Button>
              <Button
                className='password_login'
                data-event='ENTER_PAGE_PASSPORT_LOGIN'

                data-type='other'
              >
                <View className='other_login other_login'>其它方式登录</View>
              </Button>
            </View>
          </View>
        </View>

      </Block>
    )
  }
}

export default _C

```

```css
.flex {
  display: flex;
}
.flex_1 {
  display: flex;
  flex: 1;
}
.flex_center {
  align-items: center;
  justify-content: center;
}
.space_around {
  justify-content: space-around;
}
.space_between {
  justify-content: space-between;
}
.a_center {
  align-items: center;
}
.j_center {
  justify-content: center;
}
.flex_row {
  flex-direction: row;
}
.flex_column {
  flex-direction: column;
}
.flex_wrap {
  flex-wrap: wrap;
}
.flex_nowrap {
  flex-wrap: nowrap;
}
.modal {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background-color: rgba(0, 0, 0, 0.6);
  z-index: 1000;
}
.divid_line {
  color: #EAEEED;
  font-weight: normal;
  padding: 0 10px;
}
.register-modal {
  z-index: 999999;
}
.login_way_model {
  width: 560px;
  background-color: #fff;
  border-radius: 8px;
  position: relative;
}
.login_way_model .close_login {
  position: absolute;
  line-height: 80px;
  right: 0;
  color: #999;
  width: 80px;
  height: 80px;
  margin: 0;
  padding: 0;
  text-align: center;
  background: white;
}
.login_way_model .close_login .close-icon {
  width: 30px;
  height: 30px;
}
.login_way_model .close_login::after {
  display: none;
}
.login_way_model .title {
  padding: 60px 0;
  font-family: PingFangSC-Regular;
  text-align: center;
  color: #666666;
  font-size: 36px;
  line-height: 50px;
}
.login_way_model button {
  width: 460px;
  margin-bottom: 30px;
  border-radius: 10px;
  font-family: PingFangSC-Regular;
  font-size: 34px;
  height: 94px;
}
.login_way_model button .litter {
  vertical-align: middle;
}
.login_way_model button .icon {
  margin-right: 30px;
  width: 50px;
  height: 42px;
}
.login_way_model button .icon-wechat {
  margin-bottom: 8px;
}
.login_way_model button .icon-mobile {
  width: 28px;
  height: 44px;
}
.login_way_model .wx_login {
  background: #1AAD19;
  color: white;
}
.login_way_model button .wx_btn_hover {
  background: #1AAD19;
  background: rgba(0, 0, 0, 0.1);
}
.login_way_model .mobile_btn {
  background: #F8F8F8;
  color: #333;
}
.login_way_model .mobile_btn_hover {
  background: #F8F8F8;
  background: rgba(0, 0, 0, 0.1);
}
.login_way_model .other_login {
  font-family: PingFangSC-Regular;
  font-size: 26px;
  color: #666666;
}
.login_way_model .password_login {
  height: 37px;
  line-height: 37px;
  padding-top: 10px;
  padding-bottom: 75px;
  width: 100%;
  background-color: #fff;
}
.login_way_model .password_login::after {
  content: none;
}
.phone_register_model {
  width: 570px;
  background-color: #fff;
  border-radius: 20px;
  padding: 0 30px;
}
.phone_register_model .title {
  margin-top: 50px;
}
.phone_register_model .content {
  padding: 30px 0;
}
.phone_register_model .buttons {
  border-top: 1px solid #D9D9D9;
}
.phone_register_model .buttons .btn {
  margin: 30px 0;
}
.phone_register_model .buttons .btn:first-child {
  border-right: 1px solid #D9D9D9;
}
.hide {
  display: none;
}
```

**期望行为**
父子组件能正常传值

**系统信息**

![image](https://user-images.githubusercontent.com/25219300/53693303-9f38ad00-3dd9-11e9-80de-099cfed5b894.png)

 - 报错平台 百度小程序（在 Android 7.1.1，Mi Note 3 手机上）
