### ISSUE TITLE
less 引用本地图片

### ISSUE THREAD

**Issue by ANDEMEN** [NervJS/taro#2334]
**问题描述**
less 引用本地图片

**复现步骤**
```css
.img {
    background-image: url('~@img/a.png')
}
```
加不加 ~ 都无效，请问怎么引用本地图片？
