### ISSUE TITLE
更改Checkbox样式无效

### ISSUE THREAD

**Issue by lynshir** [NervJS/taro#2429]
**问题描述**
Taro组件checkbox框太大了，想改小点，不生效，使用类名和标签名都不生效

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```css
// 这里可以贴代码
.send-checkbox,
.send-checkbox::after,
.send-checkbox::before {
  width: 20px !important;
  height: 20px !important;
  border: none !important;
  background-color: red;
}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
如何修改能生效
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
