### ISSUE TITLE
less after伪类报错

### ISSUE THREAD

**Issue by pssgo** [NervJS/taro#2875]
**问题描述**
在样式中 给 Text 标签 添加样式 after伪类  无效果，并且终端报错

**复现步骤**

```less
.required {
  position: relative;
  padding-left: 30px; !important;
  &::after {
    display: block;
    content: '*';
    position: absolute;
    top: 50%;
    left: -20px;
    transform: translateY(-50%);
    line-height: inherit;
    color: red;
  }
}
```

```js

<View className={styles.row}>
      <Text className={styles.required}>名称</Text>
      <Input maxLength={30} placeholder='请输入...'  />
</View>
```

**期望行为**
可以使用 after 等伪类

**报错信息**
![image](https://user-images.githubusercontent.com/16378134/56637679-ce172500-669e-11e9-960d-5cb16ac0fbd2.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.2.17
  Taro CLI 1.2.17 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v10.8.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v10.8.0/bin/npm

**补充信息**
是否不支持 after before等伪类 还是说 不支持 Text标签那？
