### ISSUE TITLE
自定义组件 A 内的自定义组件 B 宽度为 0，需要在 #shadow-root 的父级 (component-b is="components/B") 添加宽度才显示

### ISSUE THREAD

**Issue by Garfield550** [NervJS/taro#2898]
**问题描述**

微信小程序平台自定义组件 A 内部的自定义组件 B 宽度为 0，需要在自定义组件 B 的 `<component-b is="components/B">` 添加 `style="width: 100%;"` 才有宽度。

自定义组件 B 的宽度为 100%

现象如下图
![image](https://user-images.githubusercontent.com/3471836/56800480-b29e4c80-684d-11e9-86c4-df891ce4445f.png)
![image](https://user-images.githubusercontent.com/3471836/56800526-cc3f9400-684d-11e9-9f26-86e172f567ac.png)
![image](https://user-images.githubusercontent.com/3471836/56800553-deb9cd80-684d-11e9-8300-0387a872d0a3.png)

**复现步骤**

<details>
<summary>Progress.tsx</summary>

```tsx
import { View } from '@tarojs/components';
import Taro from '@tarojs/taro';
import './Progress.scss';

'use strict';

interface Props {
  percent: number;
  strokeWidth?: number;
}

export default class CustomProgress extends Taro.Component<Props, {}> {
  public static defaultProps: Partial<Props>;
  public static options: Taro.ComponentOptions = {
    addGlobalClass: true
  };

  private renderProgressPercent(): number {
    const { percent } = this.props;
    if (percent < 0) return 0;
    if (percent > 100) return 100;
    return percent;
  }

  public render(): JSX.Element {
    const { strokeWidth } = this.props;
    const percent = this.renderProgressPercent();
    const progressBarStyle = {
      height: strokeWidth && `${+strokeWidth}px`
    };
    const progressStyle = {
      width: percent && `${+percent}%`
    };

    return (
      <View className='progress'>
        <View style={progressBarStyle}>
          <View className='progress__background' />
          <View className='progress__bar' style={progressStyle} />
        </View>
      </View>
    );
  }
}

CustomProgress.defaultProps = {
  strokeWidth: 6
};
```

</details>

<details>
<summary>Progress.scss</summary>

```scss
.progress {
  width: 100%;

  &__background {
    width: 100%;
    height: 100%;
    background-color: #f5f5f5;
  }

  &__bar {
    height: 100%;
    background-color: #ff6b00;
    background-size: 100% 100%;
    position: relative;
    top: -100%;
    left: 0;
  }
}
```

</details>

<details>
<summary>Slider.tsx</summary>

```tsx
import { Image, View } from '@tarojs/components';
import Taro from '@tarojs/taro';
import CustomProgress from './Progress';
import './Slider.scss';

'ues strict';

export default class CustomSlider extends Taro.Component {
  public static options: Taro.ComponentOptions = {
    addGlobalClass: true
  };

  public render(): JSX.Element {
    return (
      <View className='slider'>
        <View className='slider__bar'>
          <CustomProgress strokeWidth={32} percent={80} />
          <Image className='slider__bar-thumb' src='' />
        </View>
      </View>
    );
  }
}
```

</details>

<details>
<summary>Slider.scss</summary>

```scss
.slider {
  width: 100%;

  &__bar {
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    align-items: center;
    width: 100%;

    &-progress {
      width: 100%;
    }

    &-thumb {
      width: 96px;
      height: 96px;
      border-radius: 50%;
      background-color: aqua;
      position: absolute;
    }
  }
}
```

</details>

**期望行为**

自定义组件 B 能有宽度

**系统信息**

```
  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0
      Yarn: 1.15.2
      npm: 6.9.0
    npmPackages:
      @tarojs/cli: ^1.2.26 => 1.2.26 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13 
```

 - 报错平台 [weapp]
