### ISSUE TITLE
h5下createAnimation创建的动画问题

### ISSUE THREAD

**Issue by xxyGoTop** [NervJS/taro#3435]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

h5下一个元素有默认样式的时候，动画执行的样式无法覆盖其默认样式，主要原因是h5下sheet.insertRule添加的样式是添加在 [animation="taro-h5-poly-fil/...."]上，此选择器优先级低，无法覆盖默认样式

**复现步骤**
[复现问题的步骤]

首先一个元素有默认样式

```css
.selector {
   position: fixed;
   left: 0;
   bottom: -100%;
}
```

执行完动画后

```css
  [animation="taro-h5-poly-fill/2/create-animation__0"] {
      bottom: 0px; //无法覆盖掉默认的bottom: -100%的样式
      transform-origin: 50% 50% 0px;
      transition: all 400ms ease 0ms;
  }
```
执行完无法覆盖掉默认样式导致，开始并不能将元素的位置移动

**期望行为**

期望可以覆盖默认样式，或者可以给animation添加一个默认属性来增加默认样式

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.0]
 - Node.js 版本 [e.g. v11.0.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
    h5下sheet.insertRule添加的样式是添加在 [animation="taro-h5-poly-fil/...."]上，此选择器优先级低，无法覆盖默认样式
