### ISSUE TITLE
使用FunctionComponent无法正确渲染深层的CSS样式

### ISSUE THREAD

**Issue by dcalsky** [NervJS/taro#3804]
**问题描述**
定义了一个React FunctionComponent：
```tsx
import './articles.less'

export default function ArticleListComponent(props: ArticleListProps) {
  return (
    <View className="articles">
      <AtList>
        {props.articles.map(article => (
            <AtListItem
              key={article.id}
              arrow="right"
              title={article.title}
              extraText={article.create_at}
            />
        ))}
      </AtList>
    </View>
  );
}

ArticleListComponent.defaultProps = {
  articles: []
};
```

引入CSS样式(`articles.less`):
```less
.at-list__item .item-content__info-title {
  background: red;
  font-size: 0.8rem;
  white-space: normal;
}
```

发现AtListItem组件的font-size没有放大，background没有变红，white-space也没有生效。如果不封装成组件，直接在PageComponent写同样的代码，则可以成功渲染样式。【H5平台成功，WEAPP平台失败】

**期望行为**
成功渲染FunctionComponent中Components的CSS样式

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. macOS]
 - Taro 版本 [e.g. v.1.3.6]
 - Node.js 版本 [e.g. v12.4.0]
 - 报错平台 [weapp]

**补充信息**
无
