### ISSUE TITLE
H5环境下基于BEM规范写样式，会全局样式会覆盖组件内样式

### ISSUE THREAD

**Issue by calimanco** [NervJS/taro#3850]
**问题描述**
我严格遵循taro官方推荐BEM规范书写样式，也就是样式直接并没有父子关系，所有样式类都是平级的关系。
我有一个reset.scss文件引入到app.scss中，app.scss又会被app.ts引用，作为全局样式，其中有专门用来重置样式的类，会加到每一个View和Text上，以达到H5和小程序的表现一致。
这个因为小程序组件的样式隔离特性，表现是良好的。
但到了H5环境下，重置的类反而会覆盖掉组件里的样式，这样自然造成了样式丢失。

**复现步骤**
1. 在全局样式app.scss中输入以下的重置样式；
2. 在组件内的标签上使用他们；
3. 编译成H5；
4. 发现组件内的样式被他们覆盖。

```scss

.cc-view {
  display: flex;
  box-sizing: border-box;
  position: relative;
  flex-direction: column;
  flex-shrink: 0;
  flex-grow: 0;
  flex-basis: auto;
  align-items: stretch;
  align-content: flex-start;
  border: 0 solid black;
  margin: 0;
  padding: 0;
  min-width: 0;
  overflow: hidden;
}
.cc-text {
  display: block;
  box-sizing: border-box;
  position: relative;
  white-space: pre-wrap; 
  word-wrap: break-word;
  overflow: hidden; 
  flex-shrink: 0;
  flex-grow: 0;
  flex-basis: auto;
  border: 0 solid black;
  margin: 0;
  padding: 0;
  min-width: 0;
}

```

**期望行为**
组件内的样式覆盖这些“重置样式”。
最好能有类似vue里的scroped功能。

**报错信息**

无

**系统信息**

  Taro CLI 1.3.8 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.8 => 1.3.8
      @tarojs/components: 1.3.8 => 1.3.8
      @tarojs/plugin-babel: 1.3.8 => 1.3.8
      @tarojs/plugin-csso: 1.3.8 => 1.3.8
      @tarojs/plugin-sass: 1.3.8 => 1.3.8
      @tarojs/plugin-uglifyjs: 1.3.8 => 1.3.8
      @tarojs/redux: 1.3.8 => 1.3.8
      @tarojs/redux-h5: 1.3.8 => 1.3.8
      @tarojs/router: 1.3.8 => 1.3.8
      @tarojs/taro: 1.3.8 => 1.3.8
      @tarojs/taro-alipay: 1.3.8 => 1.3.8
      @tarojs/taro-h5: 1.3.8 => 1.3.8
      @tarojs/taro-swan: 1.3.8 => 1.3.8
      @tarojs/taro-tt: 1.3.8 => 1.3.8
      @tarojs/taro-weapp: 1.3.8 => 1.3.8
      @tarojs/webpack-runner: 1.3.8 => 1.3.8
      eslint-config-taro: 1.3.8 => 1.3.8
      eslint-plugin-taro: 1.3.8 => 1.3.8
      nerv-devtools: ^1.4.3 => 1.4.3
      nervjs: ^1.4.3 => 1.4.3

**补充信息**

我觉得应该是样式文件加载顺序的问题，因为样式类直接并没有父子关系，所以只能靠加载顺序决定覆盖的先后。
现在临时的解决办法是改成覆盖div和span标签，但会出现影响第三方组件的问题，比较难搞，需要一个一个手动排除。
