### ISSUE TITLE
scss 变量问题

### ISSUE THREAD

**Issue by jiangwanwei** [NervJS/taro#3916]
**问题描述**

import './index.scss'
import style from './index.module.scss'

如上，在开启cssmodule情况下引入相同的内容不同文件名的scss，index.module.scss 中使用 #{$i} 会报错, 而 index.scss则不会。

taro 1.2.23

**复现步骤**
[复现问题的步骤]
1. taro init neProject   新建一个项目，然后开启cssmodule
2. 在/page/index/index.js 中引入两个相同内容的不同文件名的scss文件
3. npm run dev:weapp

```js
// /page/index/index.js
import './index.scss'

import style from './index.module.scss'

```

```scss
@mixin rotateAni($i, $v) {  
  @keyframes rotate_#{$i} {  
    50% {  
      transform: translate(-50%, $v) rotate(180deg);  
    } 100% {  
      transform: translate(-50%, $v) rotate(360deg); 
    }  
  }  
}

@for $i from 0 through 10 {
  $y: #{'-'+ (60 + $i * 4.2) + '%'};

  .safeIdxBeforeVal_#{$i} {
    transform: translate(-50%, $y) rotate(0);  
    animation: rotate_#{$i} 6s linear infinite; 
  }
  .safeIdxAfterVal_#{$i} {
    animation: rotate_#{$i} 6s linear .5s infinite;  
    transform: translate(-50%, $y) rotate(0);  
  }

  @include rotateAni($i, $y);
}
```

**期望行为**
h5不会报错，但是小程序会报错。期望小程序也不会报错

**报错信息**

![报错截图](https://user-images.githubusercontent.com/10646630/61612915-73d43300-ac92-11e9-802a-9b8dfcc154c2.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.14.5
 - Taro 版本 v1.2.23
 - Node.js 版本 v10.15.1
 - 报错平台 [weapp, aliapp]
