### ISSUE TITLE
[微信小程序]循环动画只显示第一组

### ISSUE THREAD

**Issue by ModyQyW** [NervJS/taro#4394]
**问题描述**

微信小程序使用setInterval循环设置动画队列，但只显示了第一组动画。

**复现步骤**

- taro init taro-test，不要ts，要sass和mobx
- 替换 src/pages/index.jsx 代码如下

```jsx
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { observer } from '@tarojs/mobx'
import { observable, runInAction, computed } from 'mobx'

import './index.scss'

@observer
class Index extends Component {

  componentDidMount () {
    this.onGetCarouselText()
  }

  // 动画实例
  @observable carouselAnimation = Taro.createAnimation()

  // 动画队列
  @observable carouselAnimationData = null

  // 跑马灯文字
  @observable carouselText = ''

  // 跑马灯定时
  @observable carouselTimer = null

  // 设备信息
  @computed
  get deviceInfo () {
    return Taro.getSystemInfoSync()
  }

  // 设备宽度
  @computed
  get deviceWidth () {
    return this.deviceInfo.windowWidth
  }

  // 设备字体大小
  @computed
  get deviceFontSize () {
    return this.deviceInfo.fontSizeSetting
  }

  // X 轴偏移
  @computed
  get carouselLeft () {
    return -Math.ceil(this.deviceWidth + this.carouselText.length * 24 * this.deviceFontSize / 28)
  }

  // 模拟请求接口，获得跑马灯文字
  onGetCarouselText = () => {
    setTimeout(() => {
      runInAction(() => {
        this.carouselText = '测试跑马灯'
      })
      // 启动跑马灯
      this.onStartCarousel()
    }, 5000)
  }

  // 启动跑马灯
  onStartCarousel = () => {
    const { carouselLeft } = this
    if (carouselLeft) {
      // 设置了 X 轴偏移，导出动画队列，设置数据
      this.carouselAnimationData = this.carouselAnimation
        .translate(carouselLeft).step({ duration: 1000 })
        .translate(0).step({ duration: 0 })
        .export()
      this.carouselTimer = setInterval(() => {
        runInAction(() => {
          this.carouselAnimationData = this.carouselAnimation
            .translate(carouselLeft).step({ duration: 1000 })
            .translate(0).step({ duration: 0 })
            .export()
        })
      }, 2500)
    }
  }

  render () {
    const { carouselText, carouselAnimationData } = this
    if (!carouselText) {
      return null
    }
    return (
      <View className='index'>
        <View
          className='carousel'
          animation={carouselAnimationData}
        >
          { carouselText }
        </View>
      </View>
    )
  }
}

export default Index 
```

- 替换 src/pages/index.scss 代码如下

```scss
.index {
  position: relative;
  box-sizing: border-box;
  display: flex;
  flex-direction: row;
  align-items: center;
  width: 100%;
  height: 80rpx;
  overflow: hidden;
  background-color: white;

  .carousel {
    position: absolute;
    left: 100%;
    font-size: 24rpx;
    line-height: 40rpx;
    color: black;
    white-space: nowrap;
  }
}
```

- 替换 src/app.scss 代码如下

```scss
page {
  font-size: 28rpx;
  line-height: 44rpx;
}
```

- 根目录下`yarn dev:weapp`观察

**期望行为**

跑马灯正常循环

**报错信息**

无报错信息，执行情况不符合预期

**系统信息**

```bash
Taro CLI 1.3.17 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.17 => 1.3.17 
      @tarojs/mobx: 1.3.17 => 1.3.17 
      @tarojs/mobx-h5: 1.3.17 => 1.3.17 
      @tarojs/mobx-rn: 1.3.17 => 1.3.17 
      @tarojs/plugin-babel: 1.3.17 => 1.3.17 
      @tarojs/plugin-csso: 1.3.17 => 1.3.17 
      @tarojs/plugin-sass: 1.3.17 => 1.3.17 
      @tarojs/plugin-uglifyjs: 1.3.17 => 1.3.17 
      @tarojs/rn-runner: 1.3.17 => 1.3.17 
      @tarojs/router: 1.3.17 => 1.3.17 
      @tarojs/taro: 1.3.17 => 1.3.17 
      @tarojs/taro-alipay: 1.3.17 => 1.3.17 
      @tarojs/taro-h5: 1.3.17 => 1.3.17 
      @tarojs/taro-swan: 1.3.17 => 1.3.17 
      @tarojs/taro-tt: 1.3.17 => 1.3.17 
      @tarojs/taro-weapp: 1.3.17 => 1.3.17 
      @tarojs/webpack-runner: 1.3.17 => 1.3.17 
      eslint-config-taro: 1.3.17 => 1.3.17 
      eslint-plugin-taro: 1.3.17 => 1.3.17 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      stylelint-config-taro-rn: 1.3.17 => 1.3.17 
      stylelint-taro-rn: 1.3.17 => 1.3.17
```
