### ISSUE TITLE
<Progress /> property `borderRadius` ONLY WEAPP? use in WEB get Error `Uncaught TypeError: borderRadius`

### ISSUE THREAD

**Issue by SolidZORO** [NervJS/taro#4502]
However, this property is not in the docs. I don't know if it is an experimental property?

Here is my temporary solution.

```JSX
// jsx

<Progress borderRadius={Taro.getEnv() === 'WEAPP' ? 99 : 0}  />
```

```less
// less

.progress-bar {
  :global {
    .weui-progress__bar,
    .weui-progress__inner-bar {
      border-radius: 999px !important;
    }
  }
}
```
