### ISSUE TITLE
快应用无法使用 line-clamp 或者 lines 控制文本行数

### ISSUE THREAD

**Issue by ZakaryCode** [NervJS/taro#4607]
**问题描述**
快应用无法使用 `line-clamp` 或者 `lines` 控制文本行数

**复现步骤**

编译前
```css
.text_line_2 {
  lines: 2;
  text-overflow: ellipsis;
}
```
编译后
```css
.text_line_2 {
  text-overflow: ellipsis;
  lines: 1;
  /*lines:2; Taro comment: unsupported style.[兼容写法参考](https://doc.quickapp.cn/widgets/common-styles.html)*/
  /*-o-text-overflow:ellipsis; Taro comment: unsupported style.[兼容写法参考](https://doc.quickapp.cn/widgets/common-styles.html)*/
}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

可以使用

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
如果使用了 `text-overflow` 属性，则会自动添加 `lines:1` 而 `lines` 和 `line-clamp` 属性则被自动剔除。
