### ISSUE TITLE
h5编译错误：Module not found: Can't resolve './iconfont.eot?t=1534401198955' in 'C:\Project\.temp'

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#473]
**问题描述**
我在项目中引入了一个 iconfont 文件，提示找不到文件，但是路径是正确的，而且小程序一切正常。

**复现步骤**
`.temp`相关的目录结构如下：

```bash
│  app.js
│  app.scss
│  index.html
│  var.scss
├─iconfont
│      iconfont.eot
│      iconfont.scss
│      iconfont.svg
│      iconfont.ttf
│      iconfont.woff
```

唯一引入了`iconfont.eot`的地方是`iconfont.scss`：

```css
@font-face {font-family: "iconfont";
  src: url('iconfont.eot?t=1534401198955'); /* IE9*/
  src: url('iconfont.eot?t=1534401198955#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAABxUAAsAAAAAK9wAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABHU1VCAAABCAAAADMAAABCsP6z7U9TLzIAAAE8AAAARAAAAFY8sUpHY21hcAAAAYAAAAFkAAAD7vBowoNnbHlmAAAC5AAAFkQAACFcsx+q22hlYWQAABkoAAAAMQAAADYS5LspaGhlYQAAGVwAAAAgAAAAJAhtBDZobXR4AAAZfAAAABwAAACMjNL/+2xvY2EAABmYAAAASAAAAEiLOJUQbWF4cAAAGeAAAAAfAAAAIAFCAP5uYW1lAAAaAAAAAUUAAAJtPlT+fXBvc3QAABtIAAABCgAAAXW9qlhMeJxjYGRgYOBikGPQYWB0cfMJYeBgYGGAAJAMY05meiJQDMoDyrGAaQ4gZoOIAgCKIwNPAHicY2BkYWOcwMDKwMHUyXSGgYGhH0IzvmYwYuRgYGBiYGVmwAoC0lxTGByeMbxwYW7438AQw9zNsBsozAiSAwDm1wx1eJzdkztOI0EURU/7w4D52GMD5mMwQzxIZPxGIwKLJYBEjOQNOCUgZCdIhKyH9BqJRcAtX6eMRDr1dFpdpX5d9d69BTSBuvltGlC7ovIb1aVXq9l6ndZsvVGte37Mgb/rqKlFLaujnvoa6EhnutCNbnWnsSZ60KOe9aLX6f30/W308QHCGS211Z1nnDjj+l8Z3xqVT3bu+MNfLucxclx9EaXqBbZZZ4s+P1l2J9boseTqNvnFiuvsuvIOq+yyww/vsEibGhscMmCPfYbeduGb5/wfx0p5VE/z2WHROhRnqQruNqoF9x3VgxVAjWAtUDNYFTsmWB/UClYKzSnuVTtYPdQJ1hF1gxVFvVAcrn6wymgQrDc6CqUanQR7AJ0Gyv/OQrkRugiUPa+DvYJugl2DboP9g+6CnYTGodwwTQKl1odAqekxUHr2HOw99BJmfX4N9iPT+2BnMn0P9ihvo8DwEyY1mVl4nI05CZQbxZX1q/qU1C11t6TWjGakkTSS5h7PaKT2MfaMD5ix8W1sr00wA0lYG2Njm8Mxhz02wVkCfiHLYgP7YmZzLTFxlhDYBHOZHDibQJ6BJATIJg6QsIGEQAghEKu9v7pHw5jjvYDnV9WvX9X1f/2zRARCTp1gY4yQMplFhshSQsRsNxT6Kr1pcCozoLdSNvoKuUxWihnROI7jUakduqBozAInkwLb0EHOyRLrAlyDk/YHOpRogRHVqg/Mnx/QTuimqVdHORzxQGsFoNJKR/326VWBh6LJZEsy+fXTmiZ1JFBvqQsWqKZOCV/octhg8rXEX+vydrUKY8BXtCThfS3B/0SP36OsiQRJmpTIMDmXEMhkkeFShh+W5Xif8z3TO34j6CDmkN+yP6rJgGULMwFFUPIFkpVwSspwZF8Bh94eKJ0YUo6dPMoPzAYRbva6R8ePXn17DI+MXVMfQ9RrOmeH97wh/XONVj/KyWCEUzaY7ujECn3MZ31iTYNJm3zsJJqaoLDDZUBRBmcIhFlEJRZynw+CBiwvMlF2igOQBtkWiHvw4EH3IJB+wP/7T5Fft9337pYt797XBneUYLb7SOldd+yrX4WRi6545+7mF19svvsdT7bfY+/QG0mcdJIKGUDpkjyXHVeRbKGmMqhIUuY9tC9GH41SlREbK8kpFCeXYr7WYd+dryyZOm2xMtVOAaRsuMNOp6tH8hy5RMmHY9LOKc+GY7HVdKivfqnw6sWFUmlRqUQrreXysnJ5WmUIYKiStuFlf71bZ6d9XDTy2MB9KkTD7vmRKOwDkC7pMm8CvnpRCaW7tIL/xnXnXvY9ViYBEiN9ZAU5G/nTUSV6K32FYk/mva6DmlBkxS7gpuKrQhos1AdPx3L5Llpx8si2VSmibXES1D48l8yQexFGGpqbnebmJDySbG6u5PPJwerfcn1iJU2NYKtmmlprc5+YrlAjQBU+dJs0g0Z0uCdk0F4akNTqz/nF07Z8vR6iJbHU7C4uA9/SaYZa29TdDNd8KxQBM2lCV/M97u5QmPd3QSRpQROEg9BkhmSOaoy02e4JvLImrj/cZ7zD9rMImYsy+Dj5hH/LZcO/UnQTzizgLHOTkPlFtwGKoix7RH0Vp9TXE5sFdqkSt8tTYuNXL/uGI42bWKWcP308E9iO60IRYcc55+wQ+mdLSe1jiUwmsdJqkKiuzO4XPq1FIto66w0jYLxhnReKRELVS2WxR5QkBDLd4jUeYi9EQrBs7WWUXrbW/aW6kUXC0FRn1DUBRCM0OSwAJ8ijaCLwg1WKsuoH2ImE3OcRA0E5EJDvex8ggDL5JnudLUebIsBEm9uTk6fKQfe/f9cOndDZ9lv3CFvu/nLwTffbN90E89+axWWJjvfUD9leNhVtphc9MBGjsZyO/qOYK6MilbkjRr2wIctFW5tCzUGpIsQZHbjOYMdDsr0AdtYG6GoNxnOhUj+4VxmRK26j42g6ugFx7MDWrQcYwsUbKN2w2INhACMWM9jA5jYIZm2t7/ol0EXDh65kHH3lQ135LfP8RVsPwKN0/ZLF6yldv3jJeiIhD6PoU0dJPWkmU8kZZDk5DznJjEeJUrk0C32mXeJX7cULhpqQRdWIZUpIg005xxWH2wfSFye541z5IwdssDpamQ8wvzKyKja8dji2asQfjg1B78JeGILBE9CcHHEHR5Jc65N0FNsxl7thHTy3+lH9UdyF8s0HG3O5xkEceZ9iuEFzku8yOor7VUf9fQd9tzx2WoN3q6BcjrDH2Jmev2gi7egTZ5OFZDUhjn9fnG0ROfcvswS+AcVQXPna5co5sVT28SnPg8RyHjXkYhN3zqNTyaOezravWbudPr32ClgFC6dNWwgI99LSOHrNdvfQe2h37Gm6fe3aKxi7Yi2i9npomv4Q5D5/zGf8tRyOfAhy0dM+cu12WM0/4WHd9RNY92sTWOLZzP+yH7A0SoWoUCgW0AlI0TTEewfATzYcFMVMKMX4AHnlHgZF1gjcOLhzQIswVI++0scedNcJkhKV3XWqaqoJNWGEHmc0oEU+a4Re4aYbCSW1yJVG6F0cbMS4vlO1VUuFrfBFgUpMds9TE4qlqgn3UMhAau3J45rBPYHkL/7JkyHDCD0Nl4Lu7lGQ0iZERh4eZ7exEmYTHWQGORNjwgXoEwl6LCfGbw4PyRWb32E5BaVaa/i36988noVnV/w6LcTEeMyTeVTgHM9ET8o3Q1T5tFEP3LP4pp4Z0mMnj0nSsZ2jn4Oezy/24a7PAXxu1yiHo6Bs3rp186YtALBl87IVK5b5fw3LL17eMKkDb2eaFt+1aOnSRW73oqUwgw1kbmzKTPcbIHQgkx2gdCCbGaDuCTq33f1Z+1yAOe3Q0T6XzqD5hjz1gLuRFrThiGlGhrUC3U/z+lDYssJDep6O5x4H2GtsE+ZfmJCBROQ4sSvEKRCu/U7FsSumo6Ozkig77r4qihA7/iSKQ3L/4L6iP5ufPaPnbHbsFhqqV19gF4vuq8drVMchdvIV7f5oPpv5DwsW/lPgcOd3PB17hv2KtZIGjFJOrmZJNsqwOCF/HOfYvNs3hf/w9Xv/JIp/unfpDVOndmwZ2PeAIDywb++3tY1HXjj0K0F4/d57XxcqU+YX2wHxOMsOXevnBX9nR+kptPAOzKPPIPMneb+MnwWi2y6/l0ejC6vwvMfPL1nOT5SzBW9VubZKhzy6Rpau7h5PkvfwvA6jNWbQO70AvwszRo6ofCttJg0DewH3qO+VYNBr3a/AoMDXzvH3WMfXeaD6MIcXeADndmMiUW+aW8H3cH7zyOioH6OOon8fxDurI0W8tUkBx5KEYoE6lWaevUh55JErvM3zoCIlD1dFsfqwB7881/3tgVsu7Z8LyQOjV9fL7jf4wX8UqLNUNlgjQli9+5ZtMzjRv106Y9qr1xdG39QsS3Pf/BGvIEgIz/IgO8bm4lmiJEO6yHTMQpZiFr+BbCO7yI2EWJNOJ/N4wUVbxPv2jRGNy/Jtstczr/xHkPNE3s8+LO5xeGbHUR9Fzqsk/24tf5VPfrQ8ROlQeTzRbGhobWiIWQmARJ4D05zoQs9kylgy2eZRJvJ1daZZV5dPcIphgOEaRUMDp8CpZp8CG3rJxAblocMNbXyTn9SZ55qJBII69/sJy30USU0YsBJf+yDt8TrzOJ9G4B6FhHWMD45ZiXsmvloe/gb/LJImLJjFp93vWgn3kTpzDR8gGLfxF9nbbDNZRK7xtUWSpWJBluI8lYlX0Fs7FXT3YZCyFcwVnQqf4C5NZ5j+57KYLdaIe715EzFYleaYh+UFVxpiuVjJI3G8GFHOlfGP3wiOMZSEec5JA8OjMzb0MK0ubcqpcB0LtfZMiYkRPaFl7ABjLP/gNZ9/NsfEaDyUml5s7Frce82GZGPQMArZ+a1Tru0eXN95ScOaaXed1ykF9oSVOs2IBBvZhos3UhCV+qgsbNy4sSEUMbU6VddyxVKp2MQ2iT3dy26Vk2VD6Z6dK4kRs73NkqJ5gMaoEg59ar8iffFGvSfRs7KjrjijUY9bCy0MMdn6RDYY0sxZ3Z+CvuvPXq8K4P5GS9brlkAHWefcGS0JMZZQktmpc7vmMBbVEk2Y8bb09LToBDOM9+raJMaidoxFA+Qscg5mYpfyCpfXJdz7ROM8gnIrsEs8A0FJo+DAmyl5VPkPmbdyfJ6n4ZiUfsh8Xi6i9vPQjTc2QCtdFAapV99XefW5bXA8UxpvBukJD697NFXz/dMnRmrvA699YOWhH18USFjq1ZQGkir8WgEzQcdzrtFJhMnmXYPuUR8/+A/iv/3jjaqVCFwlMFWlvw4kTCBhlOsYO8FGPN9Xj7ItYeW3EDX7E+ST5EJyPbmL/IS8gf6+QIoYxjCYSWRyQl6cYjlFFH2Pr8BZWYqhmHC2B32GI8leDSz5+Q3aRbmvyIkYihOtIxa14yVMbhCixeCcWLuIOFpUvISw4sRtbkue1pf4/YTR4GycKRaKdm+ukJNxJ58CYSkei8r58U08Y8IT2HyT3oLTW0GTcbxN5HiUT+AeeJrenCQ7Fc4CboFcFPsczF0oedx9AyNv+PHHISyK7huP3/+WILx1vw+7z/2aIhf6I0EmqAKVVXNep6w8JMiR/gJIiiJB5xmGKlOcZNPXUZktVyhTGVu0mjFUfMV9PfuyHAzKnZoMMZOFJGrGu4p2hGE9q1GxoAQCZ1BFskKSJKTzJoVAiMmKLEAA2Rcl8QpBo5WXkUppEXBBSGeRRL4beQ8HmRkDOdSOuw+FwyowWVaEYBBYPmUwKklBS1QhBMJ2SRqZzBwyy/ZNsIewOnrPc7ICaU3G4yMfkp4DRZpLRS0NiqbQrC5x7mTq3tAJ0Mn7Cm1tA1A411PBCVmhbIUOLGjG0hbAyg2x1nk0OzuO+NsEq7/UVJAhRCmWbmC0mcllbUZn1IwXsv+OBPHZWTqvlQ1lTQBhoHkB2lwW0de0LUuabZi8ApXCMsiFplK/JTQVYlGwumrvX2+zR5mKmh3H+NnCc2/ITKq+MCTKWKzFcuWc0Y07yFKPbIi8oI9lULNy/GXDyKD9O7aDvtypzMTy4rzqnDYHwGmjD3ttt2nDHwdmSIDXNc19AGzzeffvTMG2uhCnQIREBC5YG6qThT8yFZzW6t2tfF0rXdrq9NvGHcfc9TkGWLanYX+LYR9zVxu2bcBFj4UtEcoVvCZFhR96uQmCR+lfkZN5ZDfygmbAc2zOEpYNtp9m8wg+zh8vq3lqzZOyXMZ/fuKVtl9X8nSMu0ingnqOIYTHqDRGpPFniNh4z/ZLEh7jvQqFVyPlkh/y2X9iSQJtTdV4UxsoRrKL0u5EJIgY+gpignpLLhtpjFWHY40djtPRGKPf8XrPrrtQkiKKsnWrokQk6cJ1/LViyxYPylJCkrdMIOCloB3en0ZdakvvjyTUUE+xp0MKNgRrOCumxjrndTy3F9OE2N7IWRecFXmv+41NqmrI8o4dsmyoymZZqhPlXllECKv5J1aDN+AoSR6P50+wh1g/esBWzKIxYy73dVFMoqQIyhfZdrx8Dwp96IR6UzSqU6xKDz+TzVUu3HPTntKGDaU9w9M3dj1jdGSqgwsX5tddtG5BsbgAm/ZnujZOH95zYaVS2uy+sLlUyWWfiWQ6gC09vjSPJOdtWHdWEYokdso9tUNg7Ab0wzbJkV6yhJyP2cVnyQFyK/kyuZs8SB4i/0N+Rn5OXiAvkpfIH1EX7Pgs4A5LhziGpol+sYZHDkTUYPRqMro47lLFLiqgtqS4G3Qqgh03eSJSinP3yniBKtXG3iqe2jQXC05fF+CEnaLNjq9/YcgW+FtXb9x77awN+OtHzpKlLuBJUAokEXVxFvCAoGNJj2rIn57tGHrv2js0ppfiR03kIJfyYjJWS58OiSGJiR48Y6UaVQVllRJTBWcCT6XqtyJSokfVwxCQnDpBZ88aB99x/7ZVEqWQgoe5FrqvvnJ+vyCroEbEpHUxyFHJiqODQ/8gJ2IiHev+Z+eQ+0JnWNCiGjAxfOtfQN6mMEky5Ta7sbGzsdFtj6dSHY0AqdjcvSFT1EIehCP79WAwoR3QglhhVw5KANJBGUDOrwyGw8GVoXAEnruDYz3QMIENuo+1QDwTx3/0hMJYMCRgoAhq3bMlTNsUDzYrAguFBEUQRO2vNLxkTqge/ezw6pBV+czPL6lfJOrc068JXPBJ97mbVVNgkjrrOvcvVKJKfVyOyhJIdY2ysSmdl7QnvjJ7bkCHUKCt7TPPXGYukKIKyFRsTMXhqnhjY9y9Dvmb1IcnmpjZVM882D9NTqZ0AWGj7qZBcmTZkaActsPheKT8vjEMGciVbaON8brmeYGwLPrkLFY1y8kKrGguJztRw29G/f4KIc7pP7pwlfL9nFdQ8qw4l/HzX29Q6/tOqRv4W3RtNu09zqLy8oTZqzdLflYd837OgEmPi8Xao7b4YUjw3u89zfaX5i7vnQMwpxe+2DubgoalUzHlrku1tKRUXVfh1P8FNC3AAfR38a4Hzlab9C/xzpfq+iIrwiauORLFC6yPXsaxlx1BWO3v4Rv39M4GmN3b2NIyo1iEF3ycD1PFYn+x6G6+HL9kaXAuX7oU8fB7f776e46hdqoI/FB2YwugDnM1rrV4gEiLfkkowtfj17dYlcSXkPyp+ui5/DxIcy7+uUcmvtkz537gX+0v3v8hOFwROOLxhauIl0s+wh5k8/C2NS+XbEF/ikkjVrBLsIb9FNlBriN7/Yqp9qNAnD8D5CbePW3Z+7Vp3APEJkbeDyjipAeNyXVqkXs6A/1WvORkC05ewgxuAHhCWMpj6cW4X+IZIjJt81qM1044S/8F8xl3paSqEtwlKXD66C2BPcYED8xkdB9lHqAXsgPbtt3K2K3bzrnLfef83ZTuPn+Ew5Hqq+IiQYidsWLjZRAA9yXWwSiweH/bOfB9mqNAcwFqdSxz/+Ieh/3Lv06jLLb8YxtBtOhNgRBAyNI09WZV06yQpt7utaHATV6LkwFlG3+b5p+mN3xi4pv4ffg8q59fHRIqIoWUxYTYks2/OcmmSfhBvc19U1SgQV6jYpJVvXXtYRDj+NHN1GbkvXePIsacGN4XGX949i6Dv1X1YlCJhtGFOTDGSNgwwlUO6X/tPTPaGy1Y1iZ3xVg9HDZSBv6jZ37mTMvqjPZEL3VX1I/BYZ66wKnqqXvYU2wUazaiAnfl6Hx5LWWrwOOQ3euogEUABqwi7YfdZq7XcHe6u8yenAm73V2arDdatgW7YY+ZMFO6rMFtsNvqzhnuLqRu7rbcXUiVy1rg0ZvRbE6b/KZjkhRpw4PksvzWMbpI/AHWsSqF035XmGT99IHuSOALQ4FItyiwqwPp4FNMODrppefhg08JwlMHPUjT2nMfD4EqHEaTb0ZhZyY99Zx8skaG0HsPxoMFaBXPxN+DeaaFUvASLgdFQ113poDat969VcIa4Xsh5HSECeIiRXRfdl8WlUV4HhgJpMZzltqbVep9L1ZM4r9wowHFx3/ijp/2UCU8jSxdjfsil0Nf8Lmc/EDlPuP+UtMOC1glfPw5TfF/D7sZffceYmFmUsTam/8qKEtezcWKjm2hTeXtoogYhihuc1ZcQlsrItKGe6G90LlQUyLxWz6Z33l7copBV0QXVf8crhP3CeEw1cN1Anbca6yfWlMt9w5Lzc8IBDs6G6fFacf0gfnVR2k8OjZ07T6mh6kWrufE4eqb4Xowz5w69NOhdUO+PI6zdvq8lz95765YsH7AU7A2yz1p8T92565dd7rPzlkNsHqOB+GbN7j3h8MwdMPOOwXhzga6evac1dSDfl1xu/CvqMc2mUL6yTBZiV+JF4oZr8SdVFyg6Bm6o/HHb/6KluFPPGhaafTLhT4/G5KyTqFc9PInOyrZBfRXszxj04G9q+aaq8nWePRqBbqy7PVsF6jXBRTpXT0mAF0w1VlAQU1S96uXQ4NNHzCM0PaT1TWybslrZNCt12RBj+qs4XlZWilbYQRR2qBNEaGQeqLDfSnLi7UsNHQ/q4eD7u8goklTFwAsmKpYCvyCZWgk/gu4/WxcCTJf3yEHrgroWuCqSAids/8JBSH5f60n+yB4nGNgZGBgAOJbU+6tjee3+crAzcIAAtdnW6+D0f///ndlmcTcDeRyMDCBRAGA5g3OAAAAeJxjYGRgYG7438AQwzLp/18GBpZJDEARFKAMAI7kBax4nGNhYGBgoSW2//8PVez/X6zqJjEwAAC5VgVXAAAAAAB4APoBJgGWAhoCpALAAyIDrgQ+BKAFOAVwBaIGEgZYByoH5AiQCfgKYAsSC1QMxA22Do4OwA78D0YPbA+iD/QQJBCueJxjYGRgYFBm+MQgygACTEDMBYQMDP/BfAYAJYACQQB4nGWPTU7DMBCFX/oHpBKqqGCH5AViASj9EatuWFRq911036ZOmyqJI8et1ANwHo7ACTgC3IA78EgnmzaWx9+8eWNPANzgBx6O3y33kT1cMjtyDRe4F65TfxBukF+Em2jjVbhF/U3YxzOmwm10YXmD17hi9oR3YQ8dfAjXcI1P4Tr1L+EG+Vu4iTv8CrfQ8erCPuZeV7iNRy/2x1YvnF6p5UHFockikzm/gple75KFrdLqnGtbxCZTg6BfSVOdaVvdU+zXQ+ciFVmTqgmrOkmMyq3Z6tAFG+fyUa8XiR6EJuVYY/62xgKOcQWFJQ6MMUIYZIjK6Og7VWb0r7FDwl57Vj3N53RbFNT/c4UBAvTPXFO6stJ5Ok+BPV8bUnV0K27LnpQ0kV7NSRKyQl7WtlRC6gE2ZVeOEXpc0Yk/KGdI/wAJWm7IAAAAeJxtj9tygzAMRNnExoSkbXq/X9NXPspji9hTwIxtSPn7mrSP1ZNGuzpaZYvst8rs/9phgSUYOHIIFFihxBobnOAUZ9jiHBe4xBWucYNb3OEeD3jEE57xgle84R0f2OEzE8q1LXWRBSU7FqL064OcKvruPYXAlPRxq4YQXUu+CuRHq6icbbGqbdOwIc2485p8oWSkvfMTM8nMe2e7KMKgVOIIT3XimWUvJ2Fswvlp1UsvW4rk86QOnV4r41ygKk49sVraZnNIFypNjR2TSbmhd10eSHplylmvRjtaLf6y5rXtbDCMtI1cNYnElSH1xb3dm1ge+2PmYn4wUFMLqfW8yant45RlP8v3Y8IAAA==') format('woff'),
  url('iconfont.ttf?t=1534401198955') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('iconfont.svg?t=1534401198955#iconfont') format('svg'); /* iOS 4.1- */
}
```

**期望行为**
不报错

**报错信息**
`Module not found: Can't resolve './iconfont.eot?t=1534401198955' in 'C:\Project\.temp'`

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.0.0-beta.10
 - Node.js 版本 v1.0.0-beta.10

**补充信息**
