### ISSUE TITLE
build 出的 css 有问题

### ISSUE THREAD

**Issue by BurnhamZhang** [NervJS/taro#4890]
### 问题描述
less 代码
```less
.card {
  display: flex;
  flex-direction: column;
  justify-content: space-between;

  .header {
    display: flex;
    justify-content: flex-start;
    align-items: center;
  }

  .footer {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
  }
}


```
build 结果格式化以后
```css
.card,
.card .footer {
  -webkit-box-pack: justify;
  -webkit-justify-content: space-between;
  -ms-flex-pack: justify;
  justify-content: space-between;
}
.card,
.card .footer,
.card .header {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
.card {
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
  -ms-flex-direction: column;
  flex-direction: column;
}
.card .footer,
.card .header {
  -webkit-box-pack: start;
  -webkit-justify-content: flex-start;
  -ms-flex-pack: start;
  justify-content: flex-start;
  -webkit-box-align: center;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
}
.card .footer {
  -webkit-box-align: end;
  -webkit-align-items: flex-end;
  -ms-flex-align: end;
  align-items: flex-end;
}

```

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

明显多了很多不存在的样式
footer 本来是 justify-content: space-between;
编译后被justify-content: flex-start; 覆盖了

### 系统信息

 weapp git:(master) ✗ taro info
👽 Taro v1.3.10

  Taro CLI 1.3.10 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-less: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: ^1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.1 => 1.5.1 
      nervjs: ^1.5.1 => 1.5.1 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25 

### 补充信息
```js
const path = require('path')

const config = {
  projectName: 'wechat-app',
  date: '2019-7-24',
  designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2
  },
  sourceRoot: 'src',
  outputRoot: 'dist',
  plugins: {
    babel: {
      sourceMap: true,
      presets: [
        ['env', {
          modules: false
        }]
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread'
      ]
    }
  },
  defineConstants: {
  },
  copy: {
    patterns: [
    ],
    options: {
    }
  },
  weapp: {
    lessLoaderOptions :{
      globalVars:{
          'primary-color':'#157EFB'
      }
    },
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: ['last 3 versions', 'Android >= 4.1', 'ios >= 8']
          }
        },
        pxtransform: {
          enable: true,
          config: {}
        },
        url: {
          enable: true,
          config: {
            limit: 10240 // 设定转换尺寸上限
          }
        },
        cssModules: {
          enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  },
  h5: {
    publicPath: '/',
    staticDirectory: 'static',
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: ['last 3 versions', 'Android >= 4.1', 'ios >= 8']
          }
        },
        cssModules: {
          enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  },
  alias: {
    '@': path.resolve(__dirname, '..', 'src'),
    '@/utils': path.resolve(__dirname, '..', 'src/utils'),
    '@/services': path.resolve(__dirname, '..', 'src/services')
  }
}

module.exports = function (merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  return merge({}, config, require('./prod'))
}

```

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流
