### ISSUE TITLE
1.0.0-beta.13启动服务编译报错。

### ISSUE THREAD

**Issue by JieSwift** [NervJS/taro#505]
**问题描述**
启动服务， 变异报错。

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
```cmd
生成  依赖文件  dist/base/constants/storage.js
{ [Error: expected ')' got 'u']
  message: 'expected \')\' got \'u\'',
  stack: undefined,
  type: 'Syntax',
  filename: '/Users/same/Project/Innotech/pt-godzilla/src/app.less',
  index: 134,
  line: 9,
  column: 4,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '  src: url(\'', '    url(\'', '    url(\'' ] }
编译  所有页面
(node:15483) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pages' of undefined
    at buildPages (/Users/same/Project/Innotech/pt-godzilla/node_modules/@tarojs/cli/src/weapp.js:1005:27)
    at Object.build (/Users/same/Project/Innotech/pt-godzilla/node_modules/@tarojs/cli/src/weapp.js:1783:9)
    at <anonymous>
(node:15483) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:15483) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 11.97s.
```
app.less 文件
```less
@font-face {
  font-family: 'iconfont';
  src: url('//at.alicdn.com/t/font_530636_owp9tlpo6layvi.eot');
  src: url('//at.alicdn.com/t/font_530636_owp9tlpo6layvi.eot?#iefix') format('embedded-opentype'),
    url('//at.alicdn.com/t/font_530636_owp9tlpo6layvi.woff') format('woff'),
    url('//at.alicdn.com/t/font_530636_owp9tlpo6layvi.ttf') format('truetype'),//第9行
    url('//at.alicdn.com/t/font_530636_owp9tlpo6layvi.svg#iconfont') format('svg');
}
```

**系统信息**

 - 操作系统: [e.g. mac]
 - Taro 版本 [e.g. v.1.0.13beta]
 - Node.js 版本 [e.g. v8.11.3]

**猜测**

可能是字体文件导入有问题。
