### ISSUE TITLE
LESS mixin 功能 image-width url 报错

### ISSUE THREAD

**Issue by xQuotes** [NervJS/taro#5417]
### Less 代码
```less
@r: 1px * 750 / 750;

.imgWidth(@url) {
  width: unit(image-width(@url)) * @r;
}

.imgHeight(@url) {
  height: unit(image-height(@url)) * @r;
}

.setNormalImg(@url) {
  background-image: url(@url);
  .imgWidth(@url);
  .imgHeight(@url);
  background-repeat: no-repeat;
  background-size: 100% 100%;
  background-position: center;
}

.star-wrap {
          margin-left: 100 * @r;
          .clearfix;
          .span {
            .left;
            .setNormalImg("../../assets/images/index/package-star.png");
            margin: 0 3 * @r;
          }
        }
```

### 报错信息
./.temp/components/package/index.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

            .setNormalImg("../../assets/images/index/package-star.png");
          ^
Error evaluating function `image-width`: '../../assets/images/index/package-star.png' wasn't found. Tried - /Users/q/xxx/weapp/assets/images/index/package-star.png,../../assets/images/index/package-star.png
      in /Users/q/xxx/weapp/.temp/components/package/index.less (line 45, column 12)

### 系统信息
  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
