### ISSUE TITLE
Image的aspectFit在真机测试的情况下展示不对，模拟器正常。

### ISSUE THREAD

**Issue by casatwy** [NervJS/taro#5418]
### 问题描述

Image的aspectFit在真机测试的情况下展示不对，模拟器正常。

具体是宽型图片在模拟器和真机下都正常，长型图片在模拟器下正常，真机下不正常。

图片是通过微信的【获取相册图片】功能获得的。

### 复现步骤

css内容如下(index.scss)：

```css
page {
  height: 100%;
}

.index {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.index-upper {
  width: 100%;
  display: flex;
  flex-direction: column;
  flex-grow: 1;
}

.index-image {
  width: 90vw;
  margin-left: 5vw;
  margin-top: 5vw;
  flex-grow: 1;
  flex-shrink: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: red;
}
```

jsx内容如下：

```jsx
<View className='index'>
  <View className="index-upper">
    <Image className="index-image"
      onClick={this.selectImage}
      src={this.state.selectedImage}
      mode="aspectFit" />
  </View>
</View>

```

通过微信获取相册图片的代码如下：

```js
  selectImage = async (e:ITouchEvent) => {
    e.stopPropagation()
    try {
      let result = await Taro.chooseImage({
        count: 1,
        sizeType:["compressed"],
        sourceType:["album"],
      })
      if (result.tempFilePaths.length == 1) {
        let selectedImage = result.tempFilePaths[0]
        this.setState({selectedImage})
      }
    } catch(error) {
      console.log(error)
    }
  }
```

this.selectImage会唤起微信小程序的【从相册导入图片】的功能，获得图片地址之后，再set入state的image，然后通过Image的src={this.state.image}打开图片。

在模拟器下展示的图片是正常的：

宽型图片：
<img width="354" alt="截屏2020-02-05上午9 25 35" src="https://user-images.githubusercontent.com/1005781/73803941-33d33880-47fd-11ea-8cc5-644cfc26b624.png">

长型图片：
<img width="360" alt="截屏2020-02-05上午9 25 25" src="https://user-images.githubusercontent.com/1005781/73803914-21f19580-47fd-11ea-984b-0a85abb8322c.png">

但是在真机测试的时候就不正常：

宽型图片：
![IMG_2701](https://user-images.githubusercontent.com/1005781/73803902-1b631e00-47fd-11ea-810e-d3511dd425f6.jpg)

长型图片：
![IMG_2700](https://user-images.githubusercontent.com/1005781/73803956-3c2b7380-47fd-11ea-993f-1430771cf537.jpg)

### 期望行为

像模拟器下那样正常展示

### 系统信息

👽 Taro v2.0.2

  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.2 => 2.0.2
      @tarojs/components-qa: 2.0.2 => 2.0.2
      @tarojs/mini-runner: 2.0.2 => 2.0.2
      @tarojs/router: 2.0.2 => 2.0.2
      @tarojs/taro: 2.0.2 => 2.0.2
      @tarojs/taro-alipay: 2.0.2 => 2.0.2
      @tarojs/taro-h5: 2.0.2 => 2.0.2
      @tarojs/taro-qq: 2.0.2 => 2.0.2
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2
      @tarojs/taro-rn: 2.0.2 => 2.0.2
      @tarojs/taro-swan: 2.0.2 => 2.0.2
      @tarojs/taro-tt: 2.0.2 => 2.0.2
      @tarojs/taro-weapp: 2.0.2 => 2.0.2
      @tarojs/webpack-runner: 2.0.2 => 2.0.2
      eslint-config-taro: 2.0.2 => 2.0.2
      eslint-plugin-taro: 2.0.2 => 2.0.2
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.0.2 => 2.0.2
      stylelint-taro-rn: 2.0.2 => 2.0.2

### 补充信息

真机是iPhone 11，其他的真机没有测过。
真机上安装的微信版本是7.0.10
