### ISSUE TITLE
[Feature Request] 在编译 h5 时希望能将样式中的标签选择器转换成对应的html 标签

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#542]
希望样式文件里`标签选择器`中的这些 Taro 元素 （比如`View`、`Text`）在编译 h5 时能转换成对应的`html 标签`

比如：
```css
.goods View {
  color: #666;
}
.part Text {
  font-size: .8em;
}
```
在编译 h5 时转换成：
```css
.goods div {
  color: #666;
}
.part span {
  font-size: .8em;
}
```
