### ISSUE TITLE
[Taro v3.0.0-alpha.5] Taro.createIntersectionObserver 无法使用

### ISSUE THREAD

**Issue by Psli** [NervJS/taro#5637]
### 问题描述

在 Next 版本里 Taro.createIntersectionObserver 无法使用，没有显示任何错误，同样的代码在 2.x 版本是正常使用的

### 复现步骤

index.jsx
```js
// 2.x 版本
// import Taro, { Component } from '@tarojs/taro'
import Taro from '@tarojs/taro'
import React, { Component } from 'react'
import { View, ScrollView } from '@tarojs/components'

import './index.scss'

class Index extends Component {
  config = {
    navigationBarTitleText: 'Index',
    disableScroll: true
  }

  componentDidMount() {
    this._observer = Taro.createIntersectionObserver(this)
    this._observer.relativeTo('.scroll-view').observe('.ball', res => {
      console.log(res)
    })
  }

  render() {
    return (
      <View className='index'>
        <ScrollView scrollY className='scroll-view'>
          <View className='scroll-area'>
            <View className='filling'></View>
            <View id='ball01' className='ball'></View>
          </View>
        </ScrollView>
      </View>
    )
  }
}

export default Index
```

index.scss
```scss
.scroll-view {
  display: block;
  margin-top: 100px;
  height: 400rpx;
  width: 100%;

  background: #fff;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

.scroll-area {
  height: 1300rpx;
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  transition: 0.5s;
}

.ball {
  width: 200rpx;
  height: 200rpx;
  background: #1aad19;
  border-radius: 50%;
}

.filling {
  background: red;
  width: 100%;
  height: 100rpx;
}
```

### 期望行为

能正常使用 createIntersectionObserver
