### ISSUE TITLE
scss 中 webkit 私有属性被删除

### ISSUE THREAD

**Issue by lonquan** [NervJS/taro#6434]
### 问题描述
scss 中 webkit 的私有属性, 编译后被移除

### 复现步骤
> source
```css
.multi-ellipsis-l2 {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
```
>compile
```css
.multi-ellipsis-l2 {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
}
```

### 期望行为
不移除相关私有属性  -webkit-box-orient: vertical;

### 报错信息
无

### 系统信息
```
 Taro CLI 2.2.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.6 => 2.2.6 
      @tarojs/components-qa: 2.2.6 => 2.2.6 
      @tarojs/mini-runner: 2.2.6 => 2.2.6 
      @tarojs/router: 2.2.6 => 2.2.6 
      @tarojs/taro: 2.2.6 => 2.2.6 
      @tarojs/taro-alipay: 2.2.6 => 2.2.6 
      @tarojs/taro-h5: 2.2.6 => 2.2.6 
      @tarojs/taro-qq: 2.2.6 => 2.2.6 
      @tarojs/taro-quickapp: 2.2.6 => 2.2.6 
      @tarojs/taro-rn: 2.2.6 => 2.2.6 
      @tarojs/taro-swan: 2.2.6 => 2.2.6 
      @tarojs/taro-tt: 2.2.6 => 2.2.6 
      @tarojs/taro-weapp: 2.2.6 => 2.2.6 
      @tarojs/webpack-runner: 2.2.6 => 2.2.6 
      eslint-config-taro: 2.2.6 => 2.2.6 
      eslint-plugin-taro: 2.2.6 => 2.2.6 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.2.6 => 2.2.6 
      stylelint-taro-rn: 2.2.6 => 2.2.6 
    npmGlobalPackages:
      typescript: 3.7.4
```

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail#minipostcss
配置一下 autoprefixer 就好

**Comment by lonquan** [comment]
😅 我以为是 node-sass 的问题...
`autoprefixer` 的话这样就好
```css
/* autoprefixer: off */
.multi-ellipsis-l2 {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
/* autoprefixer: on */
```
