### ISSUE TITLE
2.2.7版本ios view盒子不生效问题ios

### ISSUE THREAD

**Issue by fzzfxply** [NervJS/taro#6621]
问题描述
```
ios view最外面的盒子样式必须得加display:flex如果不加的话就会消失不见里面的内容也不显示
```
复现步骤
<View classname='test'>
<Text>1</Text>
<View>

----sass---
```css
.test{
height:50px;
width:50px;
background:red；
}
```
系统信息
taro v2.2.7

System:
macOS 10.13.6
Binaries:
Node: v12.16.3 /usr/local/bin/node
Yarn: 1.22.4 /usr/local/bin/yarn
npm: 6.14.4 /usr/local/bin/npm
