### ISSUE TITLE
[Taro Next rc-6] ellipsis 多行文字省略表现不正确

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#6800]
### 问题描述

使用该样式来省略多行文字：

```scss
.ellipsis {
	overflow: hidden;
	-o-text-overflow: ellipsis;
	text-overflow: ellipsis;
	display: -webkit-box;
	-webkit-line-clamp: 2;
	-webkit-box-orient: vertical;
}

```

实际效果：

![image](https://user-images.githubusercontent.com/22665058/85661028-289a7f80-b6ae-11ea-8ae6-46a57aba6de1.png)

在第二行末尾加了省略号是正确的，但是第二行之后的文字并没有被 `overflow: hidden`。

### 期望行为

文字在第二行末尾被截断，并且之后没有多余的文字显示。

见：<https://codesandbox.io/s/frosty-benz-wwqz4?file=/index.html>

### 系统信息

Taro 3.0.0.rc-6

### 补充信息

同样的问题出现在 h5 上。
