### ISSUE TITLE
Taro 的 Swiper 组件编译成 H5 时无法自定义宽高的bug

### ISSUE THREAD

**Issue by zenglincient** [NervJS/taro#723]
js代码
```js
<Swiper
          className='index-banner'
          circular='true'
          interval='3000'
          autoplay='true'
        >
          {
            this.state.bannerList.map( (item, index) => {
              return (
                <SwiperItem className='swiper-item' key={index}>
                  <Image className='swiper-img' src={item.url} mode='aspectFill' />
                </SwiperItem>
              )
              
            })
          }
        </Swiper>
```
样式设置
```scss
index-banner {
  width: 750px
  height: 450px
}
swiper-item {
 width: 100%
 height: 100%
}
```
在小程序端正常编译，swiper-item高度为450rpx
但是在H5端swiper-item高度为150px。
怀疑是在H5端比小程序端多了一个 swiper__wrapper 的 div。
导致获取swiper-item时高度有问题。
即便是把swiper-item样式写出成
```css
swiper-item {
 width: 100%
 height: 450px
}
```
也还是有问题
此外，在配置 display-multiple-items 属性时，配置为3，但实际H5端还是只显示一个（小程序端正常）。
多端开发时 swiper 还是很经常使用
希望能尽早点解决，谢谢
