### ISSUE TITLE
3.0.7 样式按指令进行条件编译 在build:weapp时无效

### ISSUE THREAD

**Issue by meibin08** [NervJS/taro#7410]
### 相关平台
微信小程序

**小程序基础库: 2.12.1**
**使用框架: React**

### 复现步骤
+ `npm run dev:weapp` 在样式表里使用条件指令，**有效**
```css
.login {
    position: relative;
    @include display-flex;
    @include align-items(center);

    padding: r(30) r(15) r(10);
    /* #ifdef h5 */
    font-size: 40px;
    /* #endif */
}
```
如图：
![image](https://user-images.githubusercontent.com/18324563/90882883-4ef34780-e3df-11ea-8093-77aae227a818.png)

+  `npm run build:weapp` 后**指令无效、无效** ，如图：

![image](https://user-images.githubusercontent.com/18324563/90883073-b1e4de80-e3df-11ea-9770-e2796940544a.png)

### 期望结果
`npm run build:weapp`  后，专属 h5环境的样式剔除

### 实际结果
没有剔除 h5环境的代码

### 环境信息
```
Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: 16.8.2 => 16.8.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
    npmGlobalPackages:
      typescript: 3.1.1
```
