### ISSUE TITLE
next 版本在部分android 手机上 随机无规律 element 不显示

### ISSUE THREAD

**Issue by aniu2016** [NervJS/taro#7504]
### 相关平台
H5

**浏览器版本: Mozila/5.0 （Linux；Android 9；V1938CT Build/PPR1.180610.011; wv） AppleWebKit/537.36 (KHTML，like Gecko)Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/8.2.16.1**
**使用框架: React**

### 复现步骤
在此系统自带的浏览器上, 随机无规律(暂时没找到规律) 部分element显示, 部分element不显示, 刷新后出现的问题也是一致, 在其他手机上(如iphone 6s ios13.3 iphone XSmax 13.6 小米...)无问题

### 期望结果
h5版本 兼容常见android手机

### 实际结果
在部分安卓手机上， dom 不能正常显示

### 环境信息
```
� Taro v3.0.8

Got less variables: {
  scaleNormal: '1',
  scaleSmaller: '0.8',
  scaleLarger: '1.35',
  scaleHuge: '1.5',
  userInfoHeight: '384px',       
  userInfoIconSize: '76px',      
  userInfoFooterHeight: '120px', 
  logoSizeSmall: '90px',
  logoSizeLarge: '120px',        
  goodsCellWidth: '240px',       
  goodsCellSpacing: '15px',      
  listCellIconSize: '150px',     
  listCellIconSizeSmall: '120px',
  iconSizeMini: '45px',
  iconSizeSmall: '90px',
  iconSizeLarge: '120px',        
  paddingMini: '4px',
  paddingSmall: '8px',
  paddingMiddle: '16px',
  paddingLarge: '24px',
  paddingHuge: '48px',
  fontSize: '32px',
  fontSizeMini: '22px',
  fontSizeSmaller: '26px',
  fontSizeLarger: '36px',
  fontSizeHuge: '45px',
  userInfoFooterBg: '#464645',
  userInfoHighlight: '#cfb716',
  fontColorHighlight: '#c7a56b',
  fontColor: '#9e9e9e',
  fontColorThin: 'lighten(@fontColor, 20%)',
  fontColorBold: '#363636',
  linkColor: '#44a0d4',
  primaryColor: '#dfc385',
  secondaryColor: '#bebebe',
  successColor: '#0ebe95'
}

  Taro CLI 3.0.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
手机品牌：vivo
型号: vivo x30
android 版本 : 9
vivo ROM: FuntouchOS_10
浏览器ua： Mozila/5.0 （Linux；Android 9；V1938CT Build/PPR1.180610.011; wv） AppleWebKit/537.36 (KHTML，like Gecko)Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/8.2.16.1

经排查可能是与 stencil 中使其组件显示的css有关, classname hydrated , 该 class 将 visibility: hidden; 变更为 inherit 时, 没有触发浏览器重绘, (现代码中的临时方案是针对此类机型在 页面组件 componentDidShow中 对 body display 样式 手动设置为 none; 在设置个定时器 变更为block去hack)

**Comment by Chen-jj** [comment]
提供一下 demo

**Comment by aniu2016** [comment]
[demo.zip](https://github.com/NervJS/taro/files/5275002/demo.zip)


@Chen-jj 

Demo中包含一个视频文件， 表述以上在vivo手机上出现问题

**Comment by zhangqijohn** [comment]
VIVO 绝大部分机型；

**Comment by lujijiang** [comment]
这个问题很要命啊

**Comment by lujijiang** [comment]
要尽快解决。

**Comment by Chen-jj** [comment]
此浏览器兼容问题还没找到很好的办法去解决，可以这样先绕过，副作用是使用 `visibility` 样式时控制不了子元素：

```css
// app.css
.hydrated {
  visibility: visible !important;
}
```

**Comment by Jasonzzh** [comment]
这个问题现在有解决方案吗  我也遇到了

**Comment by toFrankie** [comment]
H5 端有类似问题，大致情况：
> 页面含有 `<Video>` 组件，当切换至其他页面重新回来时，`<taro-video-core>` 组件未被添加 `.hydrated` 选择器。由于 Taro 含有一组默认的样式（如下），因此当页面切换回来的时候，`<Video>` 最终渲染的部分被隐藏了。

临时解决方法：

```scss
// scss
.video-box {
  // ...

  // 强行覆盖 Taro 默认样式
  taro-video-core {
    visibility: visible;
  }
}
```

Taro 内置默认样式

```css
taro-checkbox-core,
taro-checkbox-group-core,
taro-radio-core,
taro-radio-group-core,
taro-swiper-core,
taro-swiper-item-core,
taro-ad-core,
taro-ad-custom-core,
taro-audio-core,
taro-block-core,
taro-button-core,
taro-camera-core,
taro-canvas-core,
taro-cover-image-core,
taro-cover-view-core,
taro-custom-wrapper-core,
taro-editor-core,
taro-form-core,
taro-functional-page-navigator-core,
taro-icon-core,
taro-image-core,
taro-input-core,
taro-keyboard-accessory-core,
taro-label-core,
taro-live-player-core,
taro-live-pusher-core,
taro-map-core,
taro-match-media-core,
taro-movable-area-core,
taro-movable-view-core,
taro-navigation-bar-core,
taro-navigator-core,
taro-official-account-core,
taro-open-data-core,
taro-page-container-core,
taro-page-meta-core,
taro-picker-view-column-core,
taro-picker-view-core,
taro-progress-core,
taro-pull-to-refresh,
taro-rich-text-core,
taro-scroll-view-core,
taro-share-element-core,
taro-slider-core,
taro-slot-core,
taro-switch-core,
taro-tabbar,
taro-text-core,
taro-textarea-core,
taro-view-core,
taro-voip-room-core,
taro-web-view-core,
taro-picker-core,
taro-picker-group,
taro-video-core,
taro-video-control,
taro-video-danmu {
  visibility: hidden;
}
```
