### ISSUE TITLE
taro设计尺寸计算错误

### ISSUE THREAD

**Issue by geeeger** [NervJS/taro#8089]
### 相关平台
微信小程序

### 复现仓库
[https://github.com](https://github.com)
**小程序基础库: 2.14.0**
**使用框架: React**

### 复现步骤
config设置 
```javascript
designWidth: 375,
  deviceRatio: {
    640: 2.34 / 2,
    750: 1,
    828: 1.81 / 2,
    375: 2 / 1
  },
```
sass中 书写 
```css
.test {
 width: 375px;
}
```

### 期望结果
```css
.test {
  width: 750rpx
}
```

### 实际结果
```css
.test {
  width: 187.5rpx
}
```

### 环境信息
```
� Taro v3.0.17

(node:20460) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time

  Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 13.9.0 - D:\programmer\nodejs\node.EXE
      Yarn: 1.22.0 - D:\programmer\nodejs\yarn.CMD
      npm: 6.13.7 - D:\programmer\nodejs\npm.CMD
```
