### ISSUE TITLE
配置 `onePxTransform` 不起作用

### ISSUE THREAD

**Issue by u3u** [NervJS/taro#924]
**问题描述**

配置 `onePxTransform` 不起作用，将它配置为 `false` 依然会将 `1px` 转换成 `1rpx` 或 `0.02133rem`

**复现步骤**

```scss
@mixin setBottomLine($c: #c7c7c7) {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
  height: 1px;
  color: $c;
  content: '';
  border-bottom: 1px solid $c;
  transform: scaleY(0.5);
  transform-origin: 0 100%;
}
```

```scss
.test {
  position: relative;

  &::after {
    @include setBottomLine(#ddd);
  }
}
```

**期望行为**

将 `onePxTransform` 配置为 `false` 时应忽略 `1px` 的单位转换

**报错信息**

```css
.test {
  position: relative;
}

.test::after {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
  height: 1rpx;
  color: #ddd;
  content: '';
  border-bottom: 1rpx solid $c;
  transform: scaleY(0.5);
  transform-origin: 0 100%;
}
```

**系统信息**

- 操作系统: macOS Mojave
- Taro 版本: v1.1.0-beta.11
- Node.js 版本: v10.9.0
- 报错平台: [h5, weapp]

**临时解决方案**

```scss
/* stylelint-disable unit-case */

@mixin setBottomLine($c: #c7c7c7) {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0; // prettier-ignore
  height: 1PX;
  color: $c;
  content: ''; // prettier-ignore
  border-bottom: 1PX solid $c;
  transform: scaleY(0.5);
  transform-origin: 0 100%;
}
```
