### ISSUE TITLE
Taro Input组件的placeholderClass对H5页面不生效

### ISSUE THREAD

**Issue by Tammy-zting** [NervJS/taro#9647]
### 相关平台
H5

**浏览器版本: Chrome最新版**
**使用框架: React**

### 复现步骤
//index.jsx
```jsx
  <View className={className} style={style}>
            <Iconfont name="search"/>
            <Input
                placeholder={placeholder}
                className={`${className}__input`}
                placeholderClass={`${className}__input__placeholder`}
                onChange={handleChange}
                onBlur={handleFocus}
            />
        </View>
```

//index.scss
```scss
.cus-search {
    background-color: #f3f3f3;
    border-radius: 20Px;
    display: flex;
    flex-direction: row;
    align-items: center;
    padding: 0 10Px;
    height: 30Px;

    &__input {
        margin-left: 16px;
        flex: 1;

        &__placeholder {
            font-size: 30px;
            color: red;
        }
    }
}
```

### 期望结果
H5和小程序端显示一致

### 实际结果
小程序Input的样式修改生效，H5不生效

### 环境信息
```
👽 Taro v3.2.12


  Taro CLI 3.2.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - D:\Program Files (x86)\node.EXE
      Yarn: 1.16.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.13 - D:\Program Files (x86)\npm.CMD
```

**Comment by Tammy-zting** [comment]
上面代码效果如图

**Comment by aohanyao** [comment]
我也看到了，这里有个样式强制覆盖了，不知道怎么解决。

![image](https://user-images.githubusercontent.com/13215774/124096685-64201480-da8d-11eb-9994-875a811eb89c.png)

**Comment by ZakaryCode** [comment]
H5 暂时不支持 placeholderClass 属性

**Comment by Fujitomy** [comment]
有解决方案嘛，Textarea的placeholderClass h5也不支持，2年过去了

**Comment by Tammy-zting** [comment]
周婷婷已收到您的邮件，谢谢！！

**Comment by tmKnight01** [comment]
25年了 这个bug还没修吗....

**Comment by Tammy-zting** [comment]
周婷婷已收到您的邮件，谢谢！！

**Comment by lghuahua** [comment]
我使用的是vue，生成的html中input有一个class，可以自己控制样式，但不能使用scoped

<img width="259" height="62" alt="Image" src="https://github.com/user-attachments/assets/a3bc897c-3fdc-4664-af95-84dff4317deb" />

```scss
.input-box {
  .weui-input::placeholder {
    color: #B8BBBD;
    opacity: 1; // 确保Firefox中的placeholder可见
  }

  .weui-input::-webkit-input-placeholder {
    /* Chrome/Opera/Safari */
    color: #B8BBBD;
  }
}
```
