### ISSUE TITLE
state 中的数据不能有小数点

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro#968]
**问题描述**
想要实现打开页面，skuKeys根据skuDefault来设置选中项，如果选中，active 为true，加上class名为active。在skuKeys中，比如大小一项中，如果有如5.5这样带小数点的项，那么className={`sku ${skuItems[item].active ? 'active' : '' } ${skuItems[item].disabled ? 'disabled' : '' }` }  这句就无效了，只要改成没有小数点的名称，就没问题

**复现步骤**
[复现问题的步骤]
1. skuKeys中大小中，比如5.5改成55，那就可以正常显示，只要有小数点，就会出错

[或者可以直接贴源代码，能贴文字就不要截图]

```js
import Taro, { Component } from '@tarojs/taro'
import './index.scss'

class Demo extends Component {
  state = {
    skuKeys: {
      '颜色': {
       '红': {active: false, disabled: false, name: '红'},
       '黄': {active: false, disabled: false, name: '黄'}
      },
      '大小': {
        '5.5': {active: false, disabled: false, name: '5.5'},
        '45': {active: false, disabled: false, name: '45'}
      }
    },
    skuDefault: ['红', '5.5'],
    selectedSkus: {},
    skuSpecs: {},
    variants: {},
    selectedItem: {},
  }

  componentDidMount () {
    this.setDefault(this.state.skuKeys, this.state.skuDefault)
  }

  setDefault (ks, defaultsku) {
    const {skuKeys, skuDefault} = this.state
    let data = {}
    for (let i in skuKeys) {
      data[i] = skuKeys[i]
      for (let j in data[i]) {
        if (skuDefault.includes(j)) {
          data[i][j].active = true
        }
      }
    }
    this.setState({
      skuKeys: data
    })
  }

  render () {
    const {skuKeys} = this.state
    const skuList = Object.keys(skuKeys).map((key, index) => {
      const skuItems = skuKeys[key]
      const skuItemKeys = Object.keys(skuItems)
      return (
        <View className='item' key={index}>
           <View className="title">{key}</View>
           <View className='skus'>
             {
               skuItemKeys.map((item, idx) => {
                 return (
                  <View key={idx}
                        className={`sku ${skuItems[item].active ? 'active' : '' } ${skuItems[item].disabled ? 'disabled' : '' }` }
                  >
                    {skuItems[item].active}
                    {item}
                  </View>
                 )
               })
             }
           </View>
        </View>
      )
    })

    return (
      <View>
        {skuList}
      </View>
    )
  }
}

```

```scss
.item {
  display: flex;
 }
 .title {
  padding: 10px;
 }
.sku {
  border: 1px solid #ccc;
  padding: 10px;
  margin-right: 10px;
  // width: 60px;
  // height: 60px;
  line-height: 60px;
  text-align: center;
  font-size: 30px
}
.skus {
  display: flex;
  /*justify-content: space-around;*/
}
.active {
  color: white;
  background-color: red;
}
.disabled {
  /*color: #ddd;*/
  background-color: #ccc;
  border-color: #ccc;
  pointer-events: none;
}
```

**期望行为**
进入页面，skuDefault中的值默认选中，className加上active，比如 className='sku active'

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
<img width="284" alt="wx20181030-230813 2x" src="https://user-images.githubusercontent.com/299532/47728406-40cbb880-dc99-11e8-9802-77b2efe39d93.png">

<img width="337" alt="wx20181030-230758 2x" src="https://user-images.githubusercontent.com/299532/47728385-34dff680-dc99-11e8-9e69-35981714e39d.png">

**系统信息**

 - 操作系统: osx 10.14
 - Taro 版本 1.1.0-beta.13
 - Node.js 版本 v10.5.0
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
